---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: github-controller
  annotations:
    meta.crossplane.io/maintainer: patrick.hermann@sva.de
    meta.crossplane.io/source: github.com/stuttgart-things/stuttgart-things
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      deploys github-controller with crossplane
    meta.crossplane.io/readme: |
      deploys github-controller with crossplane
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: "v0.19.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: "v0.15.0"
