---
apiVersion: platform.stuttgart-things.com/v1alpha1
kind: FluxInitClaim
metadata:
  name: lab-flux
  namespace: crossplane-system
spec:
  helmProviderConfigRef: lab-cluster-helm
  kubernetesProviderConfigRef: lab-cluster-kubernetes
