---
apiVersion: apps.stuttgart-things.com/v1alpha1
kind: VCluster
metadata:
  name: vcluster-working-kcl
  namespace: default
  annotations:
    # Use the working KCL composition
    crossplane.io/composition-ref: xvcluster-kcl-final
spec:
  # EXACT same parameters as your working kcl run command
  name: vlcuster-k3s-tink1
  version: "0.29.0"
  clusterName: k3s-tink1
  targetNamespace: vcluster-k3s-tink2
  storageClass: local-path
  bindAddress: "0.0.0.0"
  proxyPort: 8443
  nodePort: 32445
  extraSANs:
    - test-k3s1.labul.sva.de
    - "10.31.103.23"
    - localhost
  serverUrl: https://10.31.103.23:32445
  additionalSecrets:
    - name: vc-vlcuster-k3s-tink1-crossplane
      namespace: vcluster-k3s-tink2
      context: vcluster-crossplane-context
      server: https://10.31.103.23:32445
  connectionSecret:
    enabled: true
    name: vcluster-k3s-tink2-connection
    namespace: crossplane-system
    vclusterSecretName: vc-vlcuster-k3s-tink1
    vclusterSecretNamespace: vcluster-k3s-tink2

  # Write connection secret for access
  writeConnectionSecretToRef:
    name: vcluster-working-kcl-connection
    namespace: default