---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: AnsibleRun
metadata:
  name: pdns-entry-fluxdev-2
  namespace: tekton-pipelines
spec:
  pipelineRunName: pdns-entry-labul-fluxdev-2
  inventory:
    - "all+[\"localhost\"]"
  playbooks:
    - "ansible/playbooks/pdns-ingress-entry.yaml"
  ansibleVarsFile:
    - pdns_url+-https://pdns-vsphere.labul.example.com:8443
    - entry_zone+-sthings-vsphere.labul.example.com.
    - ip_address+-10.31.102.8
    - hostname+-fluxdev-2
  gitRepoUrl: https://github.com/stuttgart-things/stuttgart-things.git
  gitRevision: main
  providerRef:
    name: in-cluster
  vaultSecretName: vault # pragma: allowlist secret
  pipelineNamespace: tekton-pipelines
  workingImage: ghcr.io/stuttgart-things/sthings-ansible:11.0.0
  roles:
    - "https://github.com/stuttgart-things/install-configure-powerdns.git"
