---
# apis/definition.yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xciliums.github.stuttgart-things.com
spec:
  group: github.stuttgart-things.com
  names:
    kind: XCilium
    plural: xciliums
  claimNames:
    kind: Cilium
    plural: ciliums
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: Name of the Cilium release
              targetNamespace:
                type: string
                description: Target namespace for Cilium installation
                default: kube-system
              version:
                type: string
                description: Cilium Helm chart version
                default: "1.19.0"
              config:
                type: string
                description: Cilium configuration profile
                default: kind
              clusterName:
                type: string
                description: Kubernetes cluster name
              kubeProxyReplacement:
                type: boolean
                description: Enable kube-proxy replacement
                default: true
              routingMode:
                type: string
                description: Routing mode (native or tunnel)
                default: native
              ipv4NativeRoutingCIDR:
                type: string
                description: IPv4 native routing CIDR
                default: "10.244.0.0/16"
              k8sServiceHost:
                type: string
                description: Kubernetes API server host
              k8sServicePort:
                type: integer
                description: Kubernetes API server port
                default: 6443
              l2announcements_enabled:
                type: boolean
                description: Enable L2 announcements
                default: true
              l2announcements_leaseDuration:
                type: string
                description: L2 announcements lease duration
                default: "3s"
              l2announcements_leaseRenewDeadline:
                type: string
                description: L2 announcements lease renew deadline
                default: "1s"
              l2announcements_leaseRetryPeriod:
                type: string
                description: L2 announcements lease retry period
                default: "500ms"
              devices:
                type: array
                description: Network devices for L2 announcements
                items:
                  type: string
                default: ["eth0", "net0"]
              externalIPs_enabled:
                type: boolean
                description: Enable external IPs
                default: true
              autoDirectNodeRoutes:
                type: boolean
                description: Enable auto direct node routes
                default: true
              operator_replicas:
                type: integer
                description: Number of Cilium operator replicas
                default: 2
            required:
            - name
            - clusterName