apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: storage-platform
  annotations:
    meta.crossplane.io/maintainer: patrick.hermann@sva.de
    meta.crossplane.io/source: https://github.com/stuttgart-things
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Storage Platform Configuration supporting multiple storage backends (OpenEBS, NFS)
    meta.crossplane.io/readme: |
      This configuration provides a unified StoragePlatform XRD and multiple
      compositions for OpenEBS and NFS CSI.
spec:
  crossplane:
    version: ">=v2.1.3"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v1.0.6"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v1.2.0"
    # Required for Pipeline compositions
    - function: xpkg.crossplane.io/crossplane-contrib/function-go-templating
      version: ">=v0.11.3"

  package:
    # APIs (XRDs)
    apis:
      - apis/definition.yaml

    # Compositions (unified composition handles both OpenEBS and NFS based on engine.type)
    compositions:
      - compositions/storageplatform.yaml

    # Optional: example claims or functions for testing
    examples:
      - examples/claim.yaml
      - examples/functions.yaml
