---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xvcluster-kcl-fixed
  labels:
    provider: kcl
    service: vcluster
spec:
  compositeTypeRef:
    apiVersion: apps.stuttgart-things.com/v1alpha1
    kind: XVCluster

  mode: Pipeline
  pipeline:
    - step: vcluster-resources
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        metadata:
          name: vcluster-kcl-function
        spec:
          source: oci://ghcr.io/stuttgart-things/xplane-vcluster
          # CRITICAL: Pass parameters to KCL module in the expected format
          params:
            oxr:
              spec:
                name: "" # Will be patched from composite resource
                version: "0.29.0" # Default, will be patched
                clusterName: "kind" # Default, will be patched
                targetNamespace: "vcluster" # Default, will be patched
                storageClass: "standard" # Default, will be patched
                bindAddress: "0.0.0.0"
                proxyPort: 8443
                nodePort: 32443
                extraSANs: ["localhost"] # Default, will be patched
                serverUrl: "https://localhost:32443" # Default, will be patched
                additionalSecrets: [] # Will be patched
                connectionSecret:
                  enabled: true
                  name: "" # Will be patched
                  namespace: "crossplane-system"
                  vclusterSecretName: "" # Will be patched
                  vclusterSecretNamespace: "" # Will be patched
      # Patch parameters from composite resource to KCL input
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        metadata:
          name: vcluster-kcl-function
        spec:
          source: oci://ghcr.io/stuttgart-things/xplane-vcluster
          params:
            oxr:
              spec: {} # This will be populated by patches
      patches:
        # Patch all parameters from XVCluster spec to KCL params
        - type: FromCompositeFieldPath
          fromFieldPath: spec
          toFieldPath: spec.params.oxr.spec
          
  # Connection secret management
  writeConnectionSecretsToNamespace: crossplane-system