---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xvcluster-exact-match
  labels:
    provider: manual
    service: vcluster
    purpose: exact-match
spec:
  compositeTypeRef:
    apiVersion: apps.stuttgart-things.com/v1alpha1
    kind: XVCluster

  mode: Resources
  resources:
    # VCluster Helm Release
    - name: vcluster-helm-release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: vlcuster-k3s-tink1
        spec:
          deletionPolicy: Delete
          forProvider:
            chart:
              name: vcluster
              repository: https://charts.loft.sh
              version: '0.29.0'
            namespace: vcluster-k3s-tink2
            values:
              controlPlane:
                statefulSet:
                  persistence:
                    volumeClaim:
                      storageClass: local-path
                distro:
                  k8s:
                    enabled: true
                proxy:
                  bindAddress: '0.0.0.0'
                  port: 8443
                  extraSANs:
                    - test-k3s1.labul.sva.de
                    - '10.31.103.23'
                    - localhost
                service:
                  enabled: true
                  spec:
                    type: NodePort
                    ports:
                      - name: https
                        port: 443
                        targetPort: 8443
                        nodePort: 32445
                        protocol: TCP
              exportKubeConfig:
                server: https://10.31.103.23:32445
                additionalSecrets:
                  - name: vc-vlcuster-k3s-tink1-crossplane
                    namespace: vcluster-k3s-tink2
                    context: vcluster-crossplane-context
                    server: https://10.31.103.23:32445
          managementPolicies:
            - '*'
          providerConfigRef:
            name: k3s-tink1
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.version
          toFieldPath: spec.forProvider.chart.version
        - type: FromCompositeFieldPath
          fromFieldPath: spec.clusterName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.targetNamespace
          toFieldPath: spec.forProvider.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.storageClass
          toFieldPath: spec.forProvider.values.controlPlane.statefulSet.persistence.volumeClaim.storageClass
        - type: FromCompositeFieldPath
          fromFieldPath: spec.nodePort
          toFieldPath: spec.forProvider.values.controlPlane.service.spec.ports[0].nodePort
        - type: FromCompositeFieldPath
          fromFieldPath: spec.extraSANs
          toFieldPath: spec.forProvider.values.controlPlane.proxy.extraSANs
        - type: FromCompositeFieldPath
          fromFieldPath: spec.serverUrl
          toFieldPath: spec.forProvider.values.exportKubeConfig.server

    # Kubeconfig Reader Object
    - name: vcluster-kubeconfig-reader
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        metadata:
          name: vcluster-kubeconfig-reader
        spec:
          deletionPolicy: Delete
          managementPolicies:
            - Observe
          providerConfigRef:
            name: k3s-tink1
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: vc-vlcuster-k3s-tink1
                namespace: vcluster-k3s-tink2
          connectionDetails:
            - apiVersion: v1
              kind: Secret
              name: vc-vlcuster-k3s-tink1
              namespace: vcluster-k3s-tink2
              fieldPath: data.config
              toConnectionSecretKey: kubeconfig
            - apiVersion: v1
              kind: Secret
              name: vc-vlcuster-k3s-tink1
              namespace: vcluster-k3s-tink2
              fieldPath: data.certificate-authority
              toConnectionSecretKey: ca.crt
          writeConnectionSecretToRef:
            name: vcluster-k3s-tink2-connection
            namespace: crossplane-system
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.clusterName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.connectionSecret.vclusterSecretName
          toFieldPath: spec.forProvider.manifest.metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.connectionSecret.vclusterSecretNamespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.connectionSecret.name
          toFieldPath: spec.writeConnectionSecretToRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.connectionSecret.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace

    # Kubernetes ProviderConfig
    - name: vcluster-kubernetes-providerconfig
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        metadata:
          name: vcluster-k3s-tink2
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: crossplane-system
              name: vcluster-k3s-tink2-connection
              key: kubeconfig
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.connectionSecret.name
          toFieldPath: spec.credentials.secretRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.connectionSecret.namespace
          toFieldPath: spec.credentials.secretRef.namespace

    # Helm ProviderConfig
    - name: vcluster-helm-providerconfig
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        metadata:
          name: vcluster-k3s-tink2-helm
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: crossplane-system
              name: vcluster-k3s-tink2-connection
              key: kubeconfig
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.connectionSecret.name
          toFieldPath: spec.credentials.secretRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.connectionSecret.namespace
          toFieldPath: spec.credentials.secretRef.namespace

    # Test Namespace in VCluster
    - name: test-namespace-in-vcluster
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        metadata:
          name: test-namespace-in-vcluster
        spec:
          deletionPolicy: Delete
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: test-namespace
                labels:
                  environment: test
                  managed-by: crossplane
          providerConfigRef:
            name: vcluster-k3s-tink2

    # Test ConfigMap in VCluster
    - name: test-configmap-in-vcluster
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        metadata:
          name: test-configmap-in-vcluster
        spec:
          deletionPolicy: Delete
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: test-config
                namespace: default
              data:
                message: "Hello from Crossplane in vcluster!"
                timestamp: "2025-10-18"
          providerConfigRef:
            name: vcluster-k3s-tink2

  # Connection secret management
  writeConnectionSecretsToNamespace: crossplane-system