---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xvcluster-kcl-with-tests
  labels:
    provider: kcl
    service: vcluster
    includes: tests
spec:
  compositeTypeRef:
    apiVersion: apps.stuttgart-things.com/v1alpha1
    kind: XVCluster

  mode: Pipeline
  pipeline:
    - step: vcluster-resources
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        metadata:
          name: vcluster-kcl-function
        spec:
          source: oci://ghcr.io/stuttgart-things/xplane-vcluster
    
    # Additional step to create test resources
    - step: test-resources
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ if .observed.composite.spec.includeTests }}
            ---
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: test-namespace-in-vcluster
              annotations:
                crossplane.io/external-name: test-namespace-in-vcluster
            spec:
              deletionPolicy: Delete
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Namespace
                  metadata:
                    name: test-namespace
                    labels:
                      environment: test
                      managed-by: crossplane
              providerConfigRef:
                name: {{ .observed.composite.spec.name | replace "vlcuster" "vcluster" }}
            ---
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: test-configmap-in-vcluster
              annotations:
                crossplane.io/external-name: test-configmap-in-vcluster
            spec:
              deletionPolicy: Delete
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: ConfigMap
                  metadata:
                    name: test-config
                    namespace: default
                  data:
                    message: "Hello from Crossplane in vcluster!"
                    timestamp: "2025-10-18"
              providerConfigRef:
                name: {{ .observed.composite.spec.name | replace "vlcuster" "vcluster" }}
            {{ end }}

  # Connection secret management
  writeConnectionSecretsToNamespace: crossplane-system