---
version: 3
vars:
  PROJECT:
    sh: echo ${PROJECT}
  BRANCH:
    sh: if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then echo $(git rev-parse --abbrev-ref HEAD); else echo main ; fi
  CROSSPLANE_PACKAGE_REGISTRY: ghcr.io
  DAGGER_CROSSPLANE_MODULE: github.com/stuttgart-things/dagger/crossplane #../dagger/crossplane #github.com/stuttgart-things/dagger/crossplane
  DAGGER_CROSSPLANE_MODULE_VERSION: v0.10.0

tasks:
  branch:
    desc: Create branch from main
    cmds:
      - git checkout main
      - git branch
      - git pull
      - |
        echo "Enter to be created (remote) branch:"
        read BRANCH_NAME;
        git checkout -b ${BRANCH_NAME}
        git push origin ${BRANCH_NAME}
      - git branch
      - git branch --set-upstream-to=origin/main ${BRANCH_NAME}

  push-configuration-package:
    desc: Push crossplane configuration package
    cmds:
      - |
        CONFIGURATION_PACKAGE_PATH={{ .ALL_CONFIGURATION_PACKAGES }}
        CONFIGURATION_PACKAGE=$(basename ${CONFIGURATION_PACKAGE_PATH})

        TAG=$(gum input --placeholder "Tag" --value "v1.0.0")

        echo "Pushing configuration package: ${CONFIGURATION_PACKAGE_PATH} with tag: ${TAG}"

        dagger call -m {{ .DAGGER_CROSSPLANE_MODULE }}@{{ .DAGGER_CROSSPLANE_MODULE_VERSION }} push \
        --src {{ .SOURCE_FOLDER }}/${CONFIGURATION_PACKAGE_PATH} \
        --progress plain --username={{ .USER }} \
        --password=env:GITHUB_TOKEN \
        --registry={{ .CROSSPLANE_PACKAGE_REGISTRY }} \
        --destination={{ .DESTINATION }}/${CONFIGURATION_PACKAGE}:${TAG}
    vars:
      DESTINATION: "{{ .CROSSPLANE_PACKAGE_REGISTRY }}/stuttgart-things/crossplane"
      USER: stuttgart-things
      SOURCE_FOLDER: "./configurations"
      ALL_CONFIGURATION_PACKAGES:
        sh: |
          find {{ .SOURCE_FOLDER }}/k8s  {{ .SOURCE_FOLDER }}/infra {{ .SOURCE_FOLDER }}/terraform {{ .SOURCE_FOLDER }}/apps -mindepth 1 -maxdepth 1 -type d | \
          sed "s|^\./configurations/||" | \
          sort | \
          gum choose

  pr:
    desc: Create pull request into main
    cmds:
      - task: commit
      - gh pr create -t "{{ .BRANCH }}" -b "{{ .BRANCH }} branch into main"
      - sleep 2s
      # - gh pr checks $(gh pr list | grep "^[^#;]" | awk '{print $1}') --watch
      - gh pr merge $(gh pr list | grep "^[^#;]" | grep '{{ .BRANCH }}' | awk '{print $1}') --auto --rebase --delete-branch
      - git checkout main && git pull

  check:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run -a

  run-pre-commit-hook:
    deps:
      - check
    desc: "Run the pre-commit hook script to replace .example.com with .example.com"
    cmds:
      - |
        # Find all YAML files in the repository recursively, excluding Taskfile.yaml
        files=$(find . -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.yml" -o -name "*.md" \) ! -name "Taskfile.yaml")

        # Loop through each file
        for file in $files; do
          # Skip binary files
          if file "$file" | grep -q "text"; then
            # Replace the string and update the file
            sed -i 's/\.sva\.de/\.example\.com/g' "$file"
          fi
        done

        # Add all modified YAML files back to staging
        git add $(git ls-files --modified | grep -E '\.ya?ml$')

        exit 0
    silent: false

  commit:
    desc: Commit + push code into branch
    deps:
      - check
    cmds:
      - git branch --set-upstream-to=origin/{{ .BRANCH }}
      - git pull
      - git status
      - |
        git add *
        git status
        if [[ -n $(git status --porcelain) ]]; then
          echo "Review the changes above."
          gum confirm "Do you want to commit these changes?" || exit 0

          echo "ENTER COMMIT MESSAGE"
          COMMIT_MESSAGE=$(gum choose "CUSTOM MESSAGE" "feat: {{ .BRANCH }}" "fix: {{ .BRANCH }}" "BREAKING CHANGE: {{ .BRANCH }}")

          if [ "$COMMIT_MESSAGE" == "CUSTOM MESSAGE" ]; then
            CHANGED_FILES=$(git status --short | awk '{print $2}' | tr '\n' ' ')
            COMMIT_MESSAGE=$(gum input --placeholder "Commit message" --value "Changed: $CHANGED_FILES")
          fi

          git commit --allow-empty -a -m "$COMMIT_MESSAGE"
        else
          echo "No changes to commit."
        fi
      - git push origin -u {{ .BRANCH }}

  merge-environment:
    desc: Merge container-use environment into main branch
    cmds:
      - |
        echo "Available environments:"
        ENVIRONMENTS=$(container-use list | tail -n +2 | awk '{print $1}' | grep -v "^$")
        if [ -z "$ENVIRONMENTS" ]; then
          echo "No environments found. Please create an environment first."
          exit 1
        fi

        echo "$ENVIRONMENTS"
        echo ""
        echo "Enter environment ID to merge:"
        read ENV_ID

        if [ -z "$ENV_ID" ]; then
          echo "No environment ID provided. Exiting."
          exit 1
        fi

        echo "Merging environment: $ENV_ID"

        # Checkout environment
        container-use checkout $ENV_ID

        # Check status
        echo "Environment status:"
        git status

        # Switch to main and merge
        git checkout main
        git merge cu-$ENV_ID

        # Push changes
        git push origin main

        echo "✅ Environment $ENV_ID successfully merged into main!"
        echo ""
        echo "🔍 View logs: container-use log $ENV_ID"
        echo "🏗️  Checkout: container-use checkout $ENV_ID"

  merge-environment-auto:
    desc: Merge specific container-use environment into main (with ENV_ID parameter)
    cmds:
      - |
        if [ -z "{{ .ENV_ID }}" ]; then
          echo "❌ Error: ENV_ID not provided"
          echo "Usage: task merge-environment-auto ENV_ID=your-env-id"
          exit 1
        fi

        echo "🔄 Merging environment: {{ .ENV_ID }}"

        # Checkout environment
        container-use checkout {{ .ENV_ID }}

        # Check status
        echo "📊 Environment status:"
        git status

        # Switch to main and merge
        echo "🔀 Switching to main and merging..."
        git checkout main
        git merge cu-{{ .ENV_ID }}

        # Push changes
        echo "🚀 Pushing changes..."
        git push origin main

        echo "✅ Environment {{ .ENV_ID }} successfully merged into main!"
        echo ""
        echo "🔍 View logs: container-use log {{ .ENV_ID }}"
        echo "🏗️  Checkout: container-use checkout {{ .ENV_ID }}"
    vars:
      ENV_ID: '{{ .ENV_ID | default "" }}'

  merge-environment-pr:
    desc: Merge container-use environment via Pull Request
    cmds:
      - |
        echo "Available environments:"
        ENVIRONMENTS=$(container-use list | tail -n +2 | awk '{print $1}' | grep -v "^$")
        if [ -z "$ENVIRONMENTS" ]; then
          echo "No environments found. Please create an environment first."
          exit 1
        fi

        echo "$ENVIRONMENTS"
        echo ""
        echo "Enter environment ID for PR:"
        read ENV_ID

        if [ -z "$ENV_ID" ]; then
          echo "No environment ID provided. Exiting."
          exit 1
        fi

        echo "Creating PR for environment: $ENV_ID"

        # Checkout environment
        container-use checkout $ENV_ID

        # Create PR title and body
        TITLE="feat: merge container-use environment $ENV_ID"
        BODY="Automated merge of container-use environment: $ENV_ID

        Environment Changes:
        - $(git log --oneline cu-$ENV_ID ^main | head -5)

        🔍 View logs: \`container-use log $ENV_ID\`
        🏗️  Checkout: \`container-use checkout $ENV_ID\`"

        # Create PR from environment branch to main
        gh pr create --base main --head cu-$ENV_ID --title "$TITLE" --body "$BODY"

        echo "✅ Pull Request created successfully!"
        echo "🔍 View logs: container-use log $ENV_ID"
        echo "🏗️  Checkout: container-use checkout $ENV_ID"

  do:
    desc: Select a task to run
    cmds:
      - |
        task=$(yq e '.tasks | keys' Taskfile.yaml | sed 's/^- //' | gum choose)
        task ${task}

  apply-crossplane-packages:
    desc: Manage Crossplane functions and configurations using Dagger Kubernetes module
    vars:
      MODULE: github.com/stuttgart-things/dagger/kubernetes
      VERSION: v0.57.0
      OPERATION:
        sh: |
          if [[ -n "${OPERATION:-}" ]]; then
            if gum confirm --default=true "OPERATION is set to '${OPERATION}'. Keep it?"; then
              echo "${OPERATION}"
            else
              gum choose "apply" "delete"
            fi
          else
            gum choose "apply" "delete"
          fi
      PACKAGE_TYPE:
        sh: |
          gum choose \
            "Functions" \
            "Configurations" \
            "Both"
      SELECTED_FUNCTIONS:
        sh: |
          package_type="{{ .PACKAGE_TYPE }}"
          if [[ "$package_type" == "Functions" || "$package_type" == "Both" ]]; then
            gum choose --no-limit --header="Select Crossplane Functions:" \
              "function-auto-ready" \
              "function-go-templating" \
              "function-kcl"
          fi
      SELECTED_CONFIGURATIONS:
        sh: |
          package_type="{{ .PACKAGE_TYPE }}"
          if [[ "$package_type" == "Configurations" || "$package_type" == "Both" ]]; then
            gum choose --no-limit --header="Select Crossplane Configurations:" \
              "github-runner" \
              "ansible-run"
          fi
      KUBECONFIG_PATH:
        sh: |
          if [[ -n "${KUBECONFIG_PATH:-}" ]]; then
            if gum confirm --default=true "KUBECONFIG_PATH is set to '${KUBECONFIG_PATH}'. Keep it?"; then
              echo "${KUBECONFIG_PATH}"
            else
              if gum confirm "Use current KUBECONFIG (${KUBECONFIG:-~/.kube/config})?"; then
                echo "${KUBECONFIG:-~/.kube/config}"
              else
                gum file ~/.kube/
              fi
            fi
          else
            if gum confirm "Use current KUBECONFIG (${KUBECONFIG:-~/.kube/config})?"; then
              echo "${KUBECONFIG:-~/.kube/config}"
            else
              gum file ~/.kube/
            fi
          fi
      KUBECONFIG_FILE:
        sh: |
          path="{{ .KUBECONFIG_PATH }}"
          eval echo "$path"
    cmds:
      - |
        selected_functions="{{ .SELECTED_FUNCTIONS }}"
        selected_configurations="{{ .SELECTED_CONFIGURATIONS }}"

        if [[ -z "$selected_functions" && -z "$selected_configurations" ]]; then
          echo "Error: No packages selected"
          exit 1
        fi

        echo "Executing kubectl operation with the following configuration:"
        echo "  Operation: {{ .OPERATION }}"

        if [[ -n "$selected_functions" ]]; then
          echo "  Selected Functions:"
          while IFS= read -r func; do
            [[ -n "$func" ]] && echo "    - $func"
          done <<< "$selected_functions"
        fi

        if [[ -n "$selected_configurations" ]]; then
          echo "  Selected Configurations:"
          while IFS= read -r config; do
            [[ -n "$config" ]] && echo "    - $config"
          done <<< "$selected_configurations"
        fi

        echo "  Kubeconfig: {{ .KUBECONFIG_FILE }}"
        echo ""
      - |
        if [[ ! -f "{{ .KUBECONFIG_FILE }}" ]]; then
          echo "Error: Kubeconfig file not found at {{ .KUBECONFIG_FILE }}"
          exit 1
        fi
      - |
        selected_functions="{{ .SELECTED_FUNCTIONS }}"
        selected_configurations="{{ .SELECTED_CONFIGURATIONS }}"
        operation="{{ .OPERATION }}"

        if gum confirm "Proceed with kubectl $operation for selected packages?"; then

          # Process Functions
          if [[ -n "$selected_functions" ]]; then
            echo ""
            echo "=== Processing Functions ==="
            while IFS= read -r function_name; do
              [[ -z "$function_name" ]] && continue

              case "$function_name" in
                "function-auto-ready")
                  func_url="https://raw.githubusercontent.com/stuttgart-things/crossplane/refs/heads/main/packages/functions/function-auto-ready.yaml"
                  ;;
                "function-go-templating")
                  func_url="https://raw.githubusercontent.com/stuttgart-things/crossplane/refs/heads/main/packages/functions/function-go-templating.yaml"
                  ;;
                "function-kcl")
                  func_url="https://raw.githubusercontent.com/stuttgart-things/crossplane/refs/heads/main/packages/functions/function-kcl.yaml"
                  ;;
                *)
                  echo "✗ Unknown function: $function_name"
                  continue
                  ;;
              esac

              echo ""
              echo "Processing function: $function_name..."

              dagger call -m {{ .MODULE }}@{{ .VERSION }} kubectl \
                --operation "$operation" \
                --url-source "$func_url" \
                --kube-config file://{{ .KUBECONFIG_FILE }}

              if [[ $? -eq 0 ]]; then
                echo "✓ Function $function_name $operation completed successfully!"
              else
                echo "✗ Function $function_name $operation failed!"
                exit 1
              fi
            done <<< "$selected_functions"
          fi

          # Process Configurations
          if [[ -n "$selected_configurations" ]]; then
            echo ""
            echo "=== Processing Configurations ==="
            while IFS= read -r config_name; do
              [[ -z "$config_name" ]] && continue

              case "$config_name" in
                "github-runner")
                  config_url="https://raw.githubusercontent.com/stuttgart-things/crossplane/refs/heads/main/packages/configurations/github-runner.yaml"
                  ;;
                "ansible-run")
                  config_url="https://raw.githubusercontent.com/stuttgart-things/crossplane/refs/heads/main/packages/configurations/ansible-run.yaml"
                  ;;
                *)
                  echo "✗ Unknown configuration: $config_name"
                  continue
                  ;;
              esac

              echo ""
              echo "Processing configuration: $config_name..."

              dagger call -m {{ .MODULE }}@{{ .VERSION }} kubectl \
                --operation "$operation" \
                --url-source "$config_url" \
                --kube-config file://{{ .KUBECONFIG_FILE }}

              if [[ $? -eq 0 ]]; then
                echo "✓ Configuration $config_name $operation completed successfully!"
              else
                echo "✗ Configuration $config_name $operation failed!"
                exit 1
              fi
            done <<< "$selected_configurations"
          fi

          echo ""
          echo "✓ All selected packages processed successfully!"
        else
          echo "Operation cancelled."
          exit 0
        fi
