---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: FluxInit
  annotations:
    meta.crossplane.io/maintainer: patrick.hermann@sva.de
    meta.crossplane.io/source: https://github.com/stuttgart-things/crossplane
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      manages lifecycle of FluxInit w/ crossplane
    meta.crossplane.io/readme: |
      manages lifecycle of FluxInit w/ crossplane
spec:
  crossplane:
    version: ">=2.13.0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.19.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.14.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-kcl
      version: ">=v0.10.4"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: ">=v0.6.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-environment-configs
      version: ">=v0.3.0"
