---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: HarvesterVM
metadata:
  name: minimal-harvester-vm
spec:
  providerConfigRef: dev
  volume:
    pvcName: minimal-harvester-vm-disk
    storageClassName: harvester-longhorn
  cloudInit:
    vmName: minimal-harvester-vm
    hostname: minimal
