apiVersion: resources.stuttgart-things.com/v1alpha1
kind: HarvesterVM
metadata:
  name: dev9
  namespace: default
spec:
  providerConfigRef: "default"  # Update this to match your ProviderConfig name

  volume:
    pvcName: dev9-disk-0
    namespace: default
    storageClassName: longhorn-image-t9w92
    storage: "20Gi"
    accessModes:
      - ReadWriteMany
    volumeMode: Block
    annotations:
      harvesterhci.io/imageId: "default/image-t9w92"

  cloudInit:
    vmName: dev9
    namespace: default
    hostname: dev9
    domain: local
    sshPasswordAuth: true
    disableRoot: false
    packageUpdate: true
    users:
      - name: sthings
        sudo: "ALL=(ALL) NOPASSWD:ALL" # pragma: allowlist secret
        lockPasswd: false
        shell: /bin/bash
        password: "Atlan7is" # pragma: allowlist secret
        sshAuthorizedKeys:
          - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC..."
    packages:
      - qemu-guest-agent
    runcmd:
      - "systemctl enable --now qemu-guest-agent.service"

  vm:
    description: "dev9-complete-vm-setup"
    runStrategy: RerunOnFailure
    evictionStrategy: LiveMigrateIfPossible
    terminationGracePeriodSeconds: 120
    os: linux
    machineType: q35
    cpu:
      cores: 4
      sockets: 1
      threads: 1
    resources:
      memory: "8Gi"
      cpu: "4"
    disks:
      - name: disk-0
        bus: virtio
        bootOrder: 1
    networks:
      - name: default
        networkName: default/vms
