apiVersion: resources.stuttgart-things.com/v1alpha1
kind: HarvesterVM
metadata:
  name: demo-harvester-vm
  namespace: default
spec:
  providerConfigRef: dev

  #################################
  # Volume (PVC)
  #################################
  volume:
    pvcName: demo-harvester-vm-root
    namespace: default
    storageClassName: harvester-longhorn
    storage: 20Gi
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    labels:
      app: demo-harvester-vm

  #################################
  # Cloud-Init
  #################################
  cloudInit:
    vmName: demo-harvester-vm
    namespace: default
    hostname: demo
    domain: stuttgart-things.local
    timezone: Europe/Berlin
    users:
      - name: ubuntu
        groups: sudo
        shell: /bin/bash
        sudo: "ALL=(ALL) NOPASSWD:ALL" # pragma: allowlist secret
        sshAuthorizedKeys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBEXAMPLEKEY user@laptop # pragma: allowlist secret
    packages:
      - qemu-guest-agent
      - curl
      - vim
    writeFiles:
      - path: /etc/motd
        owner: root:root
        permissions: "0644"
        content: |
          🚀 Welcome to your Harvester VM!
          Managed by Crossplane.
    runcmd:
      - systemctl enable qemu-guest-agent
      - systemctl start qemu-guest-agent
    packageUpdate: true
    packageUpgrade: false
    sshPasswordAuth: false
    disableRoot: true

  #################################
  # VirtualMachine
  #################################
  vm:
    description: Demo Harvester VM managed by Crossplane
    os: ubuntu
    runStrategy: RerunOnFailure
    evictionStrategy: LiveMigrateIfPossible
    terminationGracePeriodSeconds: 120

    cpu:
      cores: 4
      sockets: 1
      threads: 1

    resources:
      memory: 8Gi
      cpu: "4"

    disks:
      - name: rootdisk
        bootOrder: 1
      - name: cloudinitdisk

    networks:
      - name: default
        networkName: default/default
