---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: PostgresServer
metadata:
  name: my-postgres
spec:
  targetCluster:
    name: in-cluster
    scope: Cluster
  postgres:
    profile: medium
    namespace: postgres

    auth:
      username: appuser
      database: appdb
      existingSecret: postgres-app-credentials

    persistence:
      size: 20Gi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: false