apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: vsphere-vm
  annotations:
    meta.crossplane.io/maintainer: Stuttgart-Things <platform@stuttgart-things.com>
    meta.crossplane.io/source: github.com/stuttgart-things/crossplane
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Combined Crossplane configuration for provisioning vSphere virtual machines
      using the Terraform provider.

      This configuration provides a declarative interface for VM provisioning:
        - vSphere VM creation via Terraform provider
        - Helm-based resource management
        - Kubernetes resource orchestration

      The resulting VSphereVM resource provides a simple, declarative
      interface for VM provisioning on VMware vSphere infrastructure.

    meta.crossplane.io/readme: |
      # vSphere VM Configuration

      This Crossplane configuration provides the **VSphereVM** composite
      resource. It leverages the Terraform provider to create and manage
      virtual machines on VMware vSphere infrastructure.

      ## What this configuration does

      When a `VSphereVM` claim is created, this configuration:

      1. Provisions a virtual machine on vSphere using Terraform
      2. Manages VM lifecycle (create, update, delete)
      3. Aggregates readiness and status information on the parent resource

      ## Provided API

      ```yaml
      apiVersion: resources.stuttgart-things.com/v1alpha1
      kind: VSphereVM
      ```

      ## Minimal Example

      ```yaml
      apiVersion: resources.stuttgart-things.com/v1alpha1
      kind: VSphereVM
      metadata:
        name: my-vsphere-vm
      spec:
        providerConfigRef: terraform-provider
        vm:
          name: my-vm
          datacenter: dc1
          cluster: cluster1
          datastore: datastore1
          network: VM Network
          template: ubuntu-template
      ```

      ## Design Notes

      - Uses **Terraform provider** for vSphere resource management
      - Uses **Pipeline compositions**
      - Uses **function-patch-and-transform**
      - Integrates with Helm and Kubernetes providers for auxiliary resources

      ## Requirements

      - Crossplane v1.14+
      - Terraform provider configured with vSphere credentials
      - Helm provider configured
      - Kubernetes provider configured

spec:
  crossplane:
    version: ">=v2.1.3"

  dependsOn:
    # Required for vSphere VM provisioning via OpenTofu
    - provider: xpkg.upbound.io/upbound/provider-opentofu
      version: ">=v0.3.0"

    # Required for Pipeline compositions
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.9.3"
