---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: ProxmoxVM
metadata:
  name: test-vm
  namespace: proxmox
spec:
  vm:
    count: "1"
    name: test-vm2
    cpu: "4"
    ram: "8192"
    disk: 64G
    template: ubuntu24
    annotation: Test Proxmox VM via Crossplane
  proxmox:
    node: sthings-pve1
    datastore: v3700
    folderPath: stuttgart-things
    network: vmbr101
  tfvars:
    secretName: proxmox-tfvars # pragma: allowlist secret`
    secretNamespace: proxmox # pragma: allowlist secret`
    secretKey: terraform.tfvars # pragma: allowlist secret`
  connectionSecret:
    name: test-vm2
    namespace: default
  providerRef:
    name: proxmox-vm
  compositionRef:
    name: proxmox-vm
