---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: proxmox-vm
spec:
  configuration: |
    terraform {
      backend "kubernetes" {
        secret_suffix     = "proxmox-vm-tfstate"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
    }
