---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vsphere-vm
  labels:
    crossplane.io/xrd: vspherevms.resources.stuttgart-things.com
spec:
  compositeTypeRef:
    apiVersion: resources.stuttgart-things.com/v1alpha1
    kind: VsphereVM
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: vsphere-vm
            base:
              kind: Workspace
              apiVersion: opentofu.m.upbound.io/v1beta1
              metadata:
                annotations:
                  crossplane.io/external-name: vspherevm
              spec:
                providerConfigRef:
                  name: default
                  kind: ClusterProviderConfig
                writeConnectionSecretToRef:
                  name: vsphere-vm-test
                forProvider:
                  source: Remote
                  module: git::https://github.com/stuttgart-things/vsphere-vm.git?ref=v1.7.5-2.7.0
                  vars:
                    - key: vm_count
                      value: "1"
                    - key: vsphere_vm_name
                    - key: vm_memory
                      value: "4096"
                    - key: vm_disk_size
                      value: "64"
                    - key: vm_num_cpus
                      value: "4"
                    - key: firmware
                      value: bios
                    - key: vsphere_vm_folder_path
                    - key: vsphere_datacenter
                    - key: vsphere_datastore
                    - key: vsphere_resource_pool
                    - key: vsphere_network
                    - key: vsphere_vm_template
                    - key: bootstrap
                      value: '["echo STUTTGART-THINGS"]'
                    - key: annotation
                      value: VSPHERE-VM BUILD w/ CROSSPLANE FOR STUTTGART-THINGS
                    - key: unverified_ssl
                      value: "true"
                  varFiles:
                    - source: SecretKey
                      secretKeyRef:
                        name: vsphere-tfvars
                        key: terraform.tfvars
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.vm.name
                  strategy: string
                  string:
                    fmt: "vspherevm-%s"
                toFieldPath: "metadata.annotations[crossplane.io/external-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.count
                toFieldPath: spec.forProvider.vars[0].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.name
                toFieldPath: spec.forProvider.vars[1].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.ram
                toFieldPath: spec.forProvider.vars[2].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.disk
                toFieldPath: spec.forProvider.vars[3].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.cpu
                toFieldPath: spec.forProvider.vars[4].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.firmware
                toFieldPath: spec.forProvider.vars[5].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.folderPath
                toFieldPath: spec.forProvider.vars[6].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.datacenter
                toFieldPath: spec.forProvider.vars[7].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.datastore
                toFieldPath: spec.forProvider.vars[8].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.resourcePool
                toFieldPath: spec.forProvider.vars[9].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.network
                toFieldPath: spec.forProvider.vars[10].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.template
                toFieldPath: spec.forProvider.vars[11].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.bootstrap
                toFieldPath: spec.forProvider.vars[12].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.annotation
                toFieldPath: spec.forProvider.vars[13].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.unverifiedSsl
                toFieldPath: spec.forProvider.vars[14].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.tfvars.secretName
                toFieldPath: spec.forProvider.varFiles[0].secretKeyRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.tfvars.secretKey
                toFieldPath: spec.forProvider.varFiles[0].secretKeyRef.key
              - type: FromCompositeFieldPath
                fromFieldPath: spec.connectionSecret.name
                toFieldPath: spec.writeConnectionSecretToRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerRef.name
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerRef.kind
                toFieldPath: spec.providerConfigRef.kind
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.outputs.ip
                toFieldPath: status.share.ip
                policy:
                  fromFieldPath: Optional
