---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: github-runner
  annotations:
    meta.crossplane.io/maintainer: patrick.hermann@sva.de
    meta.crossplane.io/source: https://github.com/stuttgart-things/crossplane
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      deploys github-runner with crossplane
    meta.crossplane.io/readme: |
      deploys github-runner with crossplane
spec:
  crossplane:
    version: ">=2.13.0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.19.0"
