---
apiVersion: platform.stuttgart-things.com/v1alpha1
kind: XClusterProfile
metadata:
  name: test-cluster-profile
  namespace: crossplane-system
spec:
  helmProviderConfigRef: xplane-test-helm
  kubernetesProviderConfigRef: xplane-test-kubernetes
  cilium:
    enabled: true
    version: "1.19.2"
    k8sServiceHost: crossplane-test-control-plane
    k8sServicePort: 6443
    routingMode: native
    ipv4NativeRoutingCIDR: "10.244.0.0/16"
    autoDirectNodeRoutes: true
    devices:
      - eth0
      - net0
    operator:
      replicas: 2
    loadBalancer:
      enabled: true
      ipMode: static
      ipRange:
        start: "172.18.0.100"
        end: "172.18.0.110"
  gitops:
    engine: flux
  flux:
    instance:
      sources:
        - name: flux-infra
          kind: OCIRepository
          url: oci://ghcr.io/stuttgart-things/flux-infra
          ref: latest
        - name: flux-apps
          kind: OCIRepository
          url: oci://ghcr.io/stuttgart-things/flux-apps
          ref: latest
  certManager:
    enabled: true
    selfSigned:
      enabled: true
      wildcard:
        domain: sthings.io
