---
apiVersion: platform.stuttgart-things.com/v1alpha1
kind: XClusterProfile
metadata:
  name: test-cluster-profile
  namespace: crossplane-system
spec:
  helmProviderConfigRef: xplane-test-helm
  kubernetesProviderConfigRef: xplane-test-kubernetes
  clusterType: kind
  cilium:
    enabled: true
    clusterName: crossplane-test
  gitops:
    engine: flux
  flux:
    instance:
      sources:
        - name: flux-infra
          kind: OCIRepository
          url: oci://ghcr.io/stuttgart-things/flux-infra
          ref: latest
        - name: flux-apps
          kind: OCIRepository
          url: oci://ghcr.io/stuttgart-things/flux-apps
          ref: latest
  certManager:
    enabled: true
    selfSigned:
      enabled: true
      wildcard:
        domain: sthings.io
