---
apiVersion: platform.stuttgart-things.com/v1alpha1
kind: XClusterProfile
metadata:
  name: kind-dev-test1-profile
  namespace: crossplane-system
spec:
  clusterName: kind-dev-test1
  gitops:
    engine: none
  certManager:
    enabled: true
