---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: clusterresourcenamespaces.resources.stuttgart-things.com
  name: clusterresourcenamespace
spec:
  compositeTypeRef:
    apiVersion: resources.stuttgart-things.com/v1alpha1
    kind: ClusterResourceNamespace
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: provider
        patches:
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata:
            name: namespace
          spec:
            forProvider:
              manifest:
                apiVersion: v1
                kind: Namespace
            providerConfigRef:
              name: kubernetes-clustername
        name: namespace
        patches:
        - patchSetName: provider
          type: PatchSet
        - fromFieldPath: spec.name
          toFieldPath: metadata.name
          type: FromCompositeFieldPath
    step: patch-and-transform
  writeConnectionSecretsToNamespace: crossplane-system # pragma: allowlist secret
