---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: NetworkIntegration
metadata:
  name: test-cilium
spec:
  type: cilium
  targetCluster:
    name: target
  cilium:
    clusterName: target
    version: "1.18.5"
