---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: storageplatform-openebs
  labels:
    crossplane.io/xrd: storageplatforms.resources.stuttgart-things.com
    storage.platform.example.org/engine: openebs
spec:
  compositeTypeRef:
    apiVersion: resources.stuttgart-things.com/v1alpha1
    kind: StoragePlatform
  mode: Pipeline
  pipeline:
    - step: deploy-openebs
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $spec := .observed.composite.resource.spec -}}
            {{- $openebs := $spec.openebs -}}

            {{- $scope := $spec.targetCluster.scope | default "Namespaced" -}}
            {{- $pcKind := "ProviderConfig" -}}
            {{- if eq $scope "Cluster" -}}
            {{- $pcKind = "ClusterProviderConfig" -}}
            {{- end -}}

            {{- if $openebs.namespace }}
            ---
            apiVersion: kubernetes.m.crossplane.io/v1alpha1
            kind: Object
            metadata:
              annotations:
                {{ setResourceNameAnnotation "openebs-namespace" }}
            spec:
              providerConfigRef:
                name: {{ $spec.targetCluster.name }}
                kind: {{ $pcKind }}
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Namespace
                  metadata:
                    name: {{ $openebs.namespace }}
            {{- end }}

            ---
            apiVersion: helm.m.crossplane.io/v1beta1
            kind: Release
            metadata:
              annotations:
                {{ setResourceNameAnnotation "openebs-release" }}
            spec:
              providerConfigRef:
                name: {{ $spec.targetCluster.name }}
                kind: {{ $pcKind }}
              forProvider:
                namespace: {{ $openebs.namespace | default "openebs-system" }}
                chart:
                  name: openebs
                  repository: {{ $openebs.chartRepository | default "https://openebs.github.io/openebs" }}
                  version: {{ $openebs.version | default "4.2.0" }}
                values:
                  openebs-crds:
                    csi:
                      volumeSnapshots:
                        enabled: {{ $openebs.features.volumeSnapshots | default false }}

                  mayastor:
                    csi:
                      node:
                        initContainers:
                          enabled: {{ $openebs.features.csiNodeInitContainers | default false }}

                  engines:
                    local:
                      lvm:
                        enabled: {{ $openebs.engines.local.lvm | default false }}
                      zfs:
                        enabled: {{ $openebs.engines.local.zfs | default false }}

                    replicated:
                      mayastor:
                        enabled: {{ $openebs.engines.replicated.mayastor | default false }}

            ---
            apiVersion: resources.stuttgart-things.com/v1alpha1
            kind: StoragePlatform
            status:
              installed: true
              observedVersion: {{ $openebs.version | default "4.2.0" }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
