name: Feature Implementation
description: Implement a new feature based on SPEC.md
title: "[FEATURE] "
labels: ["feature", "spec-based"]

body:
  - type: markdown
    attributes:
      value: |
        # Feature Implementation
        Implement a new feature based on [SPEC.md](../SPEC.md)

  - type: textarea
    id: spec-section
    attributes:
      label: Affected Spec Section
      description: Which section of SPEC.md is relevant?
      placeholder: "e.g., 3.3.1 GET /claim-templates"
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Concrete requirements from the specification
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What makes this task complete?
      placeholder: |
        - [ ] Code is written
        - [ ] Write tests (80%+ coverage)
        - [ ] Code review passed
        - [ ] Documentation updated
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      options:
        - "Trivial (< 1 day)"
        - "Easy (1-2 days)"
        - "Medium (2-5 days)"
        - "Complex (1-2 weeks)"
    validations:
      required: true
