---
apiVersion: v1
kind: Secret
metadata:
  name: minio-root-secret
  namespace: artifacts
type: Opaque
stringData:
  user: minioadmin # pragma: allowlist secret
  password: supersecretpassword # pragma: allowlist secret
