apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: vsphere-vm
  annotations:
    meta.crossplane.io/maintainer: stuttgart-things
    meta.crossplane.io/description: |
      Provisions vSphere virtual machines with configurable resources,
      using EnvironmentConfig for environment-specific defaults (IDs, templates).
spec:
  crossplane:
    version: ">=2.13.0"
  dependsOn:
    - function: xpkg.upbound.io/crossplane-contrib/function-kcl
      version: ">=v0.10.4"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: ">=v0.6.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-environment-configs
      version: ">=v0.3.0"
