---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: ProxmoxVMAnsible
metadata:
  name: bibi5
  namespace: crossplane-system
spec:
  vm:
    count: "1"
    name: bibi5
    cpu: "4"
    ram: "8192"
    disk: 64G
    template: ubuntu24
    annotation: Test Proxmox VM via Crossplane
  proxmox:
    node: sthings-pve1
    datastore: v3700
    folderPath: stuttgart-things
    network: vmbr101
  tfvars:
    secretName: proxmox-tfvars # pragma: allowlist secret`
    secretNamespace: default # pragma: allowlist secret`
    secretKey: terraform.tfvars # pragma: allowlist secret`
  connectionSecret:
    name: bibi5
    namespace: default
  compositionRef:
    name: proxmox-vm-ansible
  providerRef:
    name: proxmox-vm
