---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: ProxmoxVMAnsible
metadata:
  name: bibi8
  namespace: proxmox
spec:
  vm:
    count: "1"
    name: bibi8
    cpu: "4"
    ram: "8192"
    disk: 64G
    template: ubuntu24
    annotation: Test Proxmox VM via Crossplane
  proxmox:
    node: sthings-pve1
    datastore: v3700
    folderPath: stuttgart-things
    network: vmbr101
  tfvars:
    secretName: proxmox-tfvars # pragma: allowlist secret`
    secretNamespace: proxmox # pragma: allowlist secret`
    secretKey: terraform.tfvars # pragma: allowlist secret`
  connectionSecret:
    name: bibi8
    namespace: default
  compositionRef:
    name: proxmox-vm-ansible
  providerRef:
    name: proxmox-vm
  ansible:
    pipelineRunName: back-kind-2-provisioning
    playbooks:
      - "sthings.baseos.prepare_env"
      - "sthings.baseos.setup"
      - "sthings.baseos.golang"
      - "sthings.baseos.binaries"
      - "sthings.baseos.ansible"
      - "sthings.baseos.pre_commit"
      - "sthings.baseos.semantic_release"
      - "sthings.container.docker"
      - "sthings.container.tools"
      - "sthings.container.nerdctl"
      - "sthings.container.podman"
    ansibleVarsFile:
      - "manage_filesystem+-true"
      - "update_packages+-true"
      - "install_requirements+-true"
      - "install_motd+-true"
      - "username+-sthings"
      - "lvm_home_sizing+-'15%'"
      - "lvm_root_sizing+-'35%'"
      - "lvm_root_sizing+-'35%'"
      - "lvm_var_sizing+-'50%'"
      - "event_author+-crossplane"
      - "event_tags+-ansible,baseos,crossplane,tekton"
      - "send_to_msteams+-true"
      - "reboot_all+-false"
    gitRepoUrl: https://github.com/stuttgart-things/ansible.git
    gitRevision: main
    providerRef:
      name: kubernetes-incluster
    vaultSecretName: vault  # pragma: allowlist secret
    pipelineNamespace: tekton-pipelines
    workingImage: ghcr.io/stuttgart-things/sthings-ansible:11.3.0-3
    collections:
      - https://github.com/stuttgart-things/ansible/releases/download/sthings-container-25.5.838.tar.gz/sthings-container-25.5.838.tar.gz
      - https://github.com/stuttgart-things/ansible/releases/download/sthings-rke-25.3.610/sthings-rke-25.3.610.tar.gz
      - https://github.com/stuttgart-things/ansible/releases/download/sthings-awx-25.4.1409.tar.gz/sthings-awx-25.4.1409.tar.gz
      - https://github.com/stuttgart-things/ansible/releases/download/sthings-baseos-25.5.437.tar.gz/sthings-baseos-25.5.437.tar.gz
