---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-pvc
  annotations:
    meta.crossplane.io/maintainer: Stuttgart-Things
    meta.crossplane.io/source: github.com/stuttgart-things/crossplane
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Crossplane Configuration for managing Kubernetes PersistentVolumeClaims with Harvester integration.

      Features:
      - Declarative PVC provisioning through Kubernetes API
      - Harvester image annotation support
      - Storage class and volume mode configuration
      - Multi-namespace support
      - Block and Filesystem volume modes
    meta.crossplane.io/readme: |
      # PersistentVolumeClaim Configuration

      This configuration provides a composable way to provision Kubernetes PersistentVolumeClaims through Crossplane with Harvester integration.

      ## Quick Start

      ```yaml
      apiVersion: github.stuttgart-things.com/v1alpha1
      kind: Pvc
      metadata:
        name: my-pvc
      spec:
        name: my-pvc-disk
        namespace: default
        storage: 20Gi
        storageClass: longhorn
        imageId: default/image-t9w92
      ```

      ## Configuration Options

      | Field | Type | Default | Description |
      |-------|------|---------|-------------|
      | name | string | pvc-0 | PVC resource name |
      | namespace | string | default | Target namespace |
      | storage | string | 10Gi | Storage size (10Gi, 100Gi, etc.) |
      | storageClass | string | longhorn | Storage class name |
      | volumeMode | string | Block | Volume mode (Block or Filesystem) |
      | accessModes | array | [ReadWriteMany] | Access mode configuration |
      | imageId | string | default/image-default | Harvester image ID |
      | imageNamespace | string | default | Image namespace in Harvester |

spec:
  crossplane:
    version: ">=v1.14.0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/function-kcl
      version: ">=v0.9.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.10.0"
