apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgresdb
spec:
  compositeTypeRef:
    apiVersion: resources.stuttgart-things.com/v1alpha1
    kind: PostgresDB
  mode: Pipeline
  pipeline:
    - step: create-db
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: | # pragma: allowlist secret
            {{- $xr := .observed.composite.resource }}
            {{- $ns := $xr.metadata.namespace }}
            {{- $pc := $xr.spec.providerConfigRef.name | default "default" }}

            apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
            kind: Role
            metadata:
              name: {{ $xr.spec.roleName }}
              namespace: {{ $ns }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: role
                gotemplating.fn.crossplane.io/ready: "True"
            spec:
              deletionPolicy: {{ $xr.spec.deletionPolicy }}
              forProvider:
                privileges:
                  createDb: true
                  login: true
                  createRole: true
                  inherit: true
              writeConnectionSecretToRef:
                name: {{ $xr.spec.roleName }}-secret
              providerConfigRef:
                kind: ProviderConfig
                name: {{ $pc }}

            ---
            apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
            kind: Grant
            metadata:
              name: grant-postgres-{{ $xr.spec.roleName }}
              namespace: {{ $ns }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: grant
                gotemplating.fn.crossplane.io/ready: "True"
            spec:
              deletionPolicy: {{ $xr.spec.deletionPolicy }}
              forProvider:
                role: postgres
                memberOfRef:
                  name: {{ $xr.spec.roleName }}
              providerConfigRef:
                kind: ProviderConfig
                name: {{ $pc }}

            ---
            apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
            kind: Database
            metadata:
              name: {{ $xr.spec.dbName }}
              namespace: {{ $ns }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: db
                gotemplating.fn.crossplane.io/ready: "True"
            spec:
              deletionPolicy: {{ $xr.spec.deletionPolicy }}
              forProvider:
                allowConnections: true
                owner: {{ $xr.spec.roleName }}
              providerConfigRef:
                kind: ProviderConfig
                name: {{ $pc }}
