apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: storageplatforms.storage.platform.example.org
spec:
  group: storage.platform.example.org
  scope: Namespaced
  defaultCompositeDeletePolicy: Foreground
  names:
    kind: StoragePlatform
    plural: storageplatforms
    singular: storageplatform
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: Platform-level storage offering
          properties:
            spec:
              type: object
              required:
                - engine
              properties:
                engine:
                  type: object
                  required:
                    - type
                  properties:
                    type:
                      type: string
                      description: Storage engine type
                      enum:
                        - openebs
                        - nfs
                        - ceph

                  providerConfigRef:
                    type: object
                    properties:
                      name:
                        type: string
                        default: helm-provider-cluster

                  kubernetesProviderConfigRef:
                    type: object
                    properties:
                      name:
                        type: string
                        default: kubernetes-provider-cluster

                namespace:
                  type: string
                  description: Target namespace for storage components

                version:
                  type: string
                  description: Helm chart version

                openebs:
                  type: object
                  properties:
                    profile:
                      type: string
                      enum: [localpv, mayastor, custom]
                    features:
                      type: object
                      properties:
                        volumeSnapshots:
                          type: boolean
                        csiNodeInitContainers:
                          type: boolean
                    engines:
                      type: object
                      properties:
                        local:
                          type: object
                          properties:
                            lvm:
                              type: boolean
                            zfs:
                              type: boolean
                        replicated:
                          type: object
                          properties:
                            mayastor:
                              type: boolean

                nfs:
                  type: object
                  properties:
                    serverFQDN:
                      type: string
                    sharePath:
                      type: string
                    storageClass:
                      type: string
                    reclaimPolicy:
                      type: string
                      enum: [Delete, Retain]

            status:
              type: object
              properties:
                installed:
                  type: boolean
                observedVersion:
                  type: string
