---
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: harvestervms.resources.stuttgart-things.com
spec:
  group: resources.stuttgart-things.com
  defaultCompositeDeletePolicy: Foreground
  scope: Namespaced
  names:
    kind: HarvesterVM
    plural: harvestervms
    singular: harvestervm
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - providerConfigRef
                - volume
                - cloudInit
              properties:
                providerConfigRef:
                  type: string
                  description: "Name of the ProviderConfig for Kubernetes operations"

                # Volume Claim Configuration
                volume:
                  type: object
                  required:
                    - pvcName
                    - storageClassName
                  properties:
                    pvcName:
                      type: string
                      description: "Name of the PersistentVolumeClaim"
                    namespace:
                      type: string
                      description: "PVC target namespace"
                      default: "default"
                    storageClassName:
                      type: string
                      description: "Storage class for PVC"
                    storage:
                      type: string
                      description: "PVC size (e.g., 10Gi)"
                      default: "10Gi"
                    accessModes:
                      type: array
                      items:
                        type: string
                      default:
                        - "ReadWriteOnce"
                    volumeMode:
                      type: string
                      default: "Filesystem"
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                    selector:
                      type: object
                      properties:
                        matchLabels:
                          type: object
                          additionalProperties:
                            type: string
                        matchExpressions:
                          type: array
                          items:
                            type: object
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                type: array
                                items:
                                  type: string
                    dataSource:
                      type: object
                      properties:
                        name:
                          type: string
                        kind:
                          type: string
                        apiGroup:
                          type: string
                # Cloud-Init Configuration
                cloudInit:
                  type: object
                  required:
                    - vmName
                    - hostname
                  properties:
                    vmName:
                      type: string
                      description: "VM identifier for secret naming"
                    namespace:
                      type: string
                      description: "Secret target namespace"
                      default: "vms"
                    hostname:
                      type: string
                      description: "VM hostname"
                    domain:
                      type: string
                      default: "local"
                    timezone:
                      type: string
                    users:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          sshAuthorizedKeys:
                            type: array
                            items:
                              type: string
                          sudo:
                            type: string
                          groups:
                            type: string
                          shell:
                            type: string
                          password:
                            type: string
                          lockPasswd:
                            type: boolean
                    packages:
                      type: array
                      items:
                        type: string
                    writeFiles:
                      type: array
                      items:
                        type: object
                        properties:
                          path:
                            type: string
                          content:
                            type: string
                          owner:
                            type: string
                          permissions:
                            type: string
                          encoding:
                            type: string
                    runcmd:
                      type: array
                      items:
                        type: string
                    bootcmd:
                      type: array
                      items:
                        type: string
                    packageUpdate:
                      type: boolean
                      default: true
                    packageUpgrade:
                      type: boolean
                      default: false
                    sshPasswordAuth:
                      type: boolean
                      default: false
                    disableRoot:
                      type: boolean
                      default: true
                    networkConfig:
                      type: string

            status:
              type: object
              properties:
                volume:
                  type: object
                  properties:
                    pvcName:
                      type: string
                    ready:
                      type: boolean
                cloudInit:
                  type: object
                  properties:
                    secretName:
                      type: string
                    ready:
                      type: boolean
