---
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: harvestervms.resources.stuttgart-things.com
spec:
  # Namespaced scope is the modern v2 approach (no claims support)
  scope: Namespaced
  group: resources.stuttgart-things.com
  names:
    kind: HarvesterVM
    plural: harvestervms
  # Note: claimNames removed - v2 namespaced XRs don't support claims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # Common properties
              providerConfigRef:
                type: string
                description: "Name of the ProviderConfig to use for the Kubernetes provider"
              vmName:
                type: string
                description: "Name of the VM"
              namespace:
                type: string
                description: "Namespace for the VM resources"
                default: "default"

              # PVC properties
              storage:
                type: string
                description: "Storage size for the VM disk (e.g., 50Gi)"
                default: "50Gi"
              storageClassName:
                type: string
                description: "Storage class name for the PVC"
              imageId:
                type: string
                description: "Harvester image ID for the annotation (e.g., default/image-t9w92)"
              accessModes:
                type: array
                description: "Access modes for the PVC"
                items:
                  type: string
                default:
                  - ReadWriteMany
              volumeMode:
                type: string
                description: "Volume mode (Block or Filesystem)"
                default: "Block"
              pvcAnnotations:
                type: object
                description: "Additional annotations for the PVC"
                additionalProperties:
                  type: string
              pvcLabels:
                type: object
                description: "Additional labels for the PVC"
                additionalProperties:
                  type: string

              # Cloud-init properties
              hostname:
                type: string
                description: "Hostname for the VM"
              domain:
                type: string
                description: "Domain name"
                default: "local"
              timezone:
                type: string
                description: "Timezone (e.g., UTC, Europe/Berlin)"
              users:
                type: array
                description: "User configurations"
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    sshAuthorizedKeys:
                      type: array
                      items:
                        type: string
                    sudo:
                      type: string
                    groups:
                      type: string
                    shell:
                      type: string
                    password:
                      type: string
                    lockPasswd:
                      type: boolean
              packages:
                type: array
                description: "Packages to install"
                items:
                  type: string
              writeFiles:
                type: array
                description: "Files to write"
                items:
                  type: object
                  properties:
                    path:
                      type: string
                    content:
                      type: string
                    owner:
                      type: string
                    permissions:
                      type: string
                    encoding:
                      type: string
              runcmd:
                type: array
                description: "Commands to run after boot"
                items:
                  type: string
              bootcmd:
                type: array
                description: "Commands to run during boot"
                items:
                  type: string
              packageUpdate:
                type: boolean
                description: "Update package cache"
                default: true
              packageUpgrade:
                type: boolean
                description: "Upgrade packages"
                default: false
              sshPasswordAuth:
                type: boolean
                description: "Enable SSH password authentication"
                default: false
              disableRoot:
                type: boolean
                description: "Disable root login"
                default: true
              networkConfig:
                type: string
                description: "Network configuration in cloud-init format"
            required:
            - providerConfigRef
            - vmName
            - hostname
            - storageClassName
          status:
            type: object
            properties:
              pvcName:
                type: string
                description: "Name of the created PVC"
              secretName:
                type: string
                description: "Name of the created cloud-init secret"
              namespace:
                type: string
                description: "Namespace of the created resources"
              ready:
                type: boolean