---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xproxmoxvms.resources.stuttgart-things.com
spec:
  group: resources.stuttgart-things.com
  names:
    kind: XProxmoxVM
    plural: xproxmoxvms
  claimNames:
    kind: ProxmoxVM
    plural: proxmoxvms
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vm:
                  type: object
                  properties:
                    count:
                      type: string
                      default: "1"
                    name:
                      type: string
                    cpu:
                      type: string
                      default: "4"
                    ram:
                      type: string
                      default: "4096"
                    disk:
                      type: string
                      default: "64G"
                    firmware:
                      type: string
                      default: "bios"
                    folderPath:
                      type: string
                    datastore:
                      type: string
                    network:
                      type: string
                    template:
                      type: string
                    annotation:
                      type: string
                      default: "PROXMOX-VM BUILD w/ CROSSPLANE FOR STUTTGART-THINGS"
                proxmox:
                  type: object
                  properties:
                    node:
                      type: string
                    datastore:
                      type: string
                    folderPath:
                      type: string
                    network:
                      type: string
                tfvars:
                  type: object
                  properties:
                    secretName:
                      type: string
                    secretNamespace:
                      type: string
                      default: "default"
                    secretKey:
                      type: string
                      default: "terraform.tfvars"
                  required:
                    - secretName
                connectionSecret:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                      default: "default"
                  required:
                    - name
                providerRef:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
              required:
                - vm
                - proxmox
                - tfvars
                - connectionSecret
                - providerRef
            status:
              description: A Status represents the observed state
              properties:
                share:
                  description: Freeform field containing status information
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object
