---
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: proxmoxvms.resources.stuttgart-things.com
spec:
  group: resources.stuttgart-things.com
  defaultCompositeDeletePolicy: Foreground
  scope: Namespaced
  names:
    kind: ProxmoxVM
    plural: proxmoxvms
    singular: proxmoxvm
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vm:
                  type: object
                  properties:
                    count:
                      type: string
                      default: "1"
                    name:
                      type: string
                    cpu:
                      type: string
                      default: "4"
                    ram:
                      type: string
                      default: "4096"
                    disk:
                      type: string
                      default: "32G"
                    firmware:
                      type: string
                      default: "seabios"
                    template:
                      type: string
                    annotation:
                      type: string
                      default: "PROXMOX-VM BUILD w/ CROSSPLANE FOR STUTTGART-THINGS"
                  required:
                    - name
                    - template
                proxmox:
                  type: object
                  properties:
                    node:
                      type: string
                    datastore:
                      type: string
                    folderPath:
                      type: string
                    network:
                      type: string
                  required:
                    - node
                    - datastore
                    - network
                tfvars:
                  type: object
                  properties:
                    secretName:
                      type: string
                    secretKey:
                      type: string
                      default: terraform.tfvars
                  required:
                    - secretName
                connectionSecret:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
                providerRef:
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                      default: ClusterProviderConfig
                      enum:
                        - ProviderConfig
                        - ClusterProviderConfig
                  required:
                    - name
              required:
                - vm
                - proxmox
                - tfvars
                - connectionSecret
                - providerRef
            status:
              description: A Status represents the observed state
              properties:
                share:
                  description: Freeform field containing status information
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object
