---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: ansibleruns.resources.stuttgart-things.com
  name: ansible-run
spec:
  compositeTypeRef:
    apiVersion: resources.stuttgart-things.com/v1alpha1
    kind: AnsibleRun
  mode: Pipeline
  pipeline:
  - step: create-ansiblerun
    functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      metadata:
        name: ansiblerun
      spec:
        source: oci://ghcr.io/stuttgart-things/kcl-tekton-pr:0.4.1
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready