---
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: ansibleruns.resources.stuttgart-things.com
spec:
  group: resources.stuttgart-things.com
  defaultCompositeDeletePolicy: Foreground
  scope: Namespaced
  names:
    kind: AnsibleRun
    plural: ansibleruns
    singular: ansiblerun
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Pipeline Configuration
                pipelineRunName:
                  type: string
                  description: Name of the Tekton PipelineRun
                namespace:
                  type: string
                  description: Namespace where the pipeline will run
                  default: tekton-ci

                # Storage Configuration
                storageSize:
                  type: string
                  description: Size of the storage volume
                  default: "20Mi"
                storageAccessModes:
                  type: string
                  description: Storage access mode
                  default: ReadWriteOnce

                # Ansible Configuration
                ansibleWorkingImage:
                  type: string
                  description: Ansible working container image
                  default: ghcr.io/stuttgart-things/sthings-ansible:11.11.0
                createInventory:
                  type: string
                  description: Whether to create an Ansible inventory
                  default: "true"
                  enum: ["true", "false"]
                ansibleTargetHost:
                  type: string
                  description: Ansible target host
                  default: all
                ansibleVerbosity:
                  type: string
                  description: Ansible verbosity level
                  default: "2"
                validateInventory:
                  type: string
                  description: Whether to validate the inventory
                  default: "true"
                  enum: ["true", "false"]
                # Git Configuration
                gitRepoUrl:
                  type: string
                  description: Git repository URL
                  default: https://github.com/stuttgart-things/stage-time.git
                gitRevision:
                  type: string
                  description: Git branch or revision
                  default: main
                gitPath:
                  type: string
                  description: Path to the pipeline file in the Git repository
                gitWorkspaceSubdirectory:
                  type: string
                  description: Workspace subdirectory for Ansible
                  default: /ansible/workdir/

                # Credentials
                ansibleCredentialsSecretName:
                  type: string
                  description: Name of the secret containing Ansible credentials
                  default: ansible-credentials
                ansibleCredentialsUserKey:
                  type: string
                  description: Key for the Ansible user in the credentials secret
                  default: ANSIBLE_USER
                ansibleCredentialsPasswordKey:
                  type: string
                  description: Key for the Ansible password in the credentials secret
                  default: ANSIBLE_PASSWORD

                # Ansible Roles and Collections
                installExtraRoles:
                  type: string
                  description: Whether to install extra Ansible roles
                  default: "true"
                  enum: ["true", "false"]
                ansibleExtraRoles:
                  type: array
                  description: List of extra Ansible roles to install
                  items:
                    type: string
                installExtraCollections:
                  type: string
                  description: Whether to install extra Ansible collections
                  default: "true"
                  enum: ["true", "false"]
                ansibleExtraCollections:
                  type: array
                  description: List of extra Ansible collections to install
                  items:
                    type: string

                # Playbooks and Variables
                ansiblePlaybooks:
                  type: array
                  description: List of Ansible playbooks to execute
                  items:
                    type: string
                ansibleVarsFile:
                  type: array
                  description: List of Ansible variables from file
                  items:
                    type: string
                ansibleVarsInventory:
                  type: array
                  description: List of Ansible inventory variables
                  items:
                    type: string

                # Crossplane Configuration
                wrapInCrossplane:
                  type: boolean
                  description: Whether to wrap the pipeline in Crossplane
                  default: true
                crossplaneObjectName:
                  type: string
                  description: Name of the Crossplane object
                crossplaneNamespace:
                  type: string
                  description: Namespace for the Crossplane object
                  default: default
                crossplaneProviderConfig:
                  type: string
                  description: Crossplane provider config to use
                  default: kubernetes-provider
                crossplaneTimeout:
                  type: string
                  description: Timeout for Crossplane operations
                  default: "60"

              required:
                - pipelineRunName
                - namespace
                - gitRepoUrl
                - ansiblePlaybooks
