---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: VsphereVmAnsible
metadata:
  name: dev-may2
  namespace: default
spec:
  providerRef:
    name: default
    kind: ClusterProviderConfig
  vm:
    count: "1"
    name: dev-may2
    cpu: "8"
    ram: "4096"
    disk: "64"
    firmware: bios
    folderPath: stuttgart-things/testing
    datacenter: /LabUL
    datastore: /LabUL/datastore/UL-ESX-SAS-01
    resourcePool: /LabUL/host/Cluster-V6.5/Resources
    network: /LabUL/network/LAB-10.31.103
    template: sthings-u24
    bootstrap: '["echo STUTTGART-THINGS"]'
    annotation: VSPHERE-VM BUILD w/ CROSSPLANE FOR STUTTGART-THINGS
    unverifiedSsl: "true"
  tfvars:
    secretName: vsphere-tfvars  # pragma: allowlist secret
    secretNamespace: default  # pragma: allowlist secret
    secretKey: terraform.tfvars  # pragma: allowlist secret
  connectionSecret:
    name: dev-may2
    namespace: default
  ansible:
    pipelineRunName: dev-may2-provisioning-1
    playbooks:
      - "sthings.baseos.prepare_env"
      - "sthings.baseos.dev"
    ansibleVarsFile:
      - tmp_dir+-'/home/nonroot/.ansible/tmp'
      - become_local_user+-true
      - local_user+-nonroot
      - "manage_filesystem+-true"
      - "update_packages+-true"
      - "install_requirements+-true"
      - "install_motd+-true"
      - "username+-sthings"
      - "lvm_home_sizing+-'15%'"
      - "lvm_root_sizing+-'35%'"
      - "lvm_root_sizing+-'35%'"
      - "lvm_var_sizing+-'50%'"
      - "event_author+-crossplane"
      - "event_tags+-ansible,baseos,crossplane,tekton"
      - "send_to_msteams+-true"
      - "reboot_all+-false"
    gitRepoUrl: https://github.com/stuttgart-things/ansible.git
    gitRevision: main
    providerRef:
      name: in-cluster
    vaultSecretName: vault  # pragma: allowlist secret
    pipelineNamespace: tekton-pipelines
    workingImage: ghcr.io/stuttgart-things/sthings-ansible:11.3.0-3
    collections:
      - community.crypto:2.22.3
      - community.general:10.1.0
      - ansible.posix:2.0.0
      - kubernetes.core:5.0.0
      - community.docker:4.1.0
      - community.vmware:5.2.0
      - awx.awx:24.6.1
      - community.hashi_vault:6.2.0
      - ansible.netcommon:7.1.0
      - https://github.com/stuttgart-things/ansible/releases/download/sthings-baseos-25.3.629.tar.gz/sthings-baseos-25.3.629.tar.gz
      - https://github.com/stuttgart-things/ansible/releases/download/sthings-container-25.3.635.tar.gz/sthings-container-25.3.635.tar.gz
      - https://github.com/stuttgart-things/ansible/releases/download/sthings-awx-25.3.762.tar.gz/sthings-awx-25.3.762.tar.gz
      - https://github.com/stuttgart-things/ansible/releases/download/sthings-rke-25.6.1057.tar.gz/sthings-rke-25.6.1057.tar.gz
