---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: default
type: Opaque
stringData:
  credentials.tfvars: |
    harbor_username = "<REPLACE-ME>"
    harbor_password = "<REPLACE-ME>"
