---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vsphere-vm-ansible
  labels:
    crossplane.io/xrd: vspherevmansibles.resources.stuttgart-things.com
spec:
  compositeTypeRef:
    apiVersion: resources.stuttgart-things.com/v1alpha1
    kind: VsphereVmAnsible
  mode: Pipeline
  pipeline:
    - step: create-vsphere-vm
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: vsphere-vm
            base:
              apiVersion: resources.stuttgart-things.com/v1alpha1
              kind: VsphereVM
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.namespace
                toFieldPath: metadata.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.count
                toFieldPath: spec.vm.count
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.name
                toFieldPath: spec.vm.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.cpu
                toFieldPath: spec.vm.cpu
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.ram
                toFieldPath: spec.vm.ram
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.disk
                toFieldPath: spec.vm.disk
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.firmware
                toFieldPath: spec.vm.firmware
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.folderPath
                toFieldPath: spec.vm.folderPath
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.datacenter
                toFieldPath: spec.vm.datacenter
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.datastore
                toFieldPath: spec.vm.datastore
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.resourcePool
                toFieldPath: spec.vm.resourcePool
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.network
                toFieldPath: spec.vm.network
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.template
                toFieldPath: spec.vm.template
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.bootstrap
                toFieldPath: spec.vm.bootstrap
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.annotation
                toFieldPath: spec.vm.annotation
              - type: FromCompositeFieldPath
                fromFieldPath: spec.vm.unverifiedSsl
                toFieldPath: spec.vm.unverifiedSsl
              - type: FromCompositeFieldPath
                fromFieldPath: spec.tfvars.secretName
                toFieldPath: spec.tfvars.secretName
              - type: FromCompositeFieldPath
                fromFieldPath: spec.tfvars.secretKey
                toFieldPath: spec.tfvars.secretKey
              - type: FromCompositeFieldPath
                fromFieldPath: spec.connectionSecret.name
                toFieldPath: spec.connectionSecret.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerRef.name
                toFieldPath: spec.providerRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerRef.kind
                toFieldPath: spec.providerRef.kind
              - type: ToCompositeFieldPath
                fromFieldPath: status.share.ip
                toFieldPath: status.share.ip
                policy:
                  fromFieldPath: Required
                transforms:
                  - type: string
                    string:
                      type: Join
                      join:
                        separator: ','
                  - type: string
                    string:
                      type: TrimPrefix
                      trim: '['
                  - type: string
                    string:
                      type: TrimSuffix
                      trim: ']'
                  - type: string
                    string:
                      type: Format
                      fmt: all+["%s"]
              - type: ToCompositeFieldPath
                fromFieldPath: status.share.ip
                toFieldPath: status.share.ips
                policy:
                  fromFieldPath: Required
                transforms:
                  - type: string
                    string:
                      type: Join
                      join:
                        separator: '-'
    - step: create-ansible-inventory
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: create-ansible-inventory
            base:
              apiVersion: opentofu.m.upbound.io/v1beta1
              kind: Workspace
              metadata:
                annotations:
                  crossplane.io/external-name: create-ansible-inventory
              spec:
                providerConfigRef:
                  name: default
                  kind: ClusterProviderConfig
                forProvider:
                  source: Inline
                  vars:
                    - key: ipAddrs
                      value: pat
                  module: |
                    provider "random" {}

                    locals {
                      ip_addresses = split("-", var.ipAddrs)
                    }

                    resource "random_shuffle" "shuffled_ips" {
                      input        = local.ip_addresses
                      result_count = length(local.ip_addresses) # Shuffle all IPs
                    }

                    output "ips" {
                      value = var.ipAddrs
                    }

                    output "ansible_inventory" {
                      value = <<EOT
                    [initial_master_node]
                    ${random_shuffle.shuffled_ips.result[0]}

                    [additional_master_nodes]
                    %{ for ip in slice(random_shuffle.shuffled_ips.result, 1, length(local.ip_addresses)) ~}
                    ${ip}
                    %{ endfor ~}
                    EOT
                    }

                    variable "ipAddrs" {
                      description = "Ip addresses"
                      type        = string
                    }
                writeConnectionSecretToRef:
                  name: terraform-workspace-create-ansible-inventory
            patches:
              - type: CombineFromComposite
                combine:
                  strategy: string
                  string:
                    fmt: 'create-inventory-%s'
                  variables:
                    - fromFieldPath: metadata.name
                toFieldPath: metadata.name
              - type: CombineFromComposite
                combine:
                  strategy: string
                  string:
                    fmt: 'inventory-%s'
                  variables:
                    - fromFieldPath: metadata.name
                toFieldPath: spec.writeConnectionSecretToRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: status.share.ips
                toFieldPath: spec.forProvider.vars[0].value
                policy:
                  fromFieldPath: Required
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerRef.name
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerRef.kind
                toFieldPath: spec.providerConfigRef.kind
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.outputs.ansible_inventory
                toFieldPath: status.share.ansible_inventory
                policy:
                  fromFieldPath: Required
                transforms:
                  - type: string
                    string:
                      type: Convert
                      convert: "ToBase64"
    - step: create-pipelinerun-id
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: create-pipelinerun-id
            base:
              apiVersion: opentofu.m.upbound.io/v1beta1
              kind: Workspace
              metadata:
                annotations:
                  crossplane.io/external-name: create-pipelinerun-id
              spec:
                providerConfigRef:
                  name: default
                  kind: ClusterProviderConfig
                forProvider:
                  source: Inline
                  vars:
                    - key: ipAddrs
                      value: unset
                    - key: provisioning
                      value: unset
                  module: |
                    provider "local" {}

                    locals {
                      ip_addresses = split("-", var.ipAddrs)
                    }

                    # Combine the calendar date and IP addresses to create a unique, deterministic ID
                    resource "null_resource" "generate_id" {
                      triggers = {
                        # Format the current timestamp to get only the calendar date (YYYY-MM-DD)
                        current_day = formatdate("YYYY-MM-DD", timestamp())
                        ips         = join(",", local.ip_addresses)
                      }
                    }

                    output "generated_id" {
                      value = substr(sha256("${null_resource.generate_id.triggers.current_day}-${null_resource.generate_id.triggers.ips}-${var.provisioning}"), -12, -1)
                    }

                    variable "ipAddrs" {
                      description = "Ip addresses"
                      type        = string
                    }

                    variable "provisioning" {
                      description = "provisioning name"
                      default     = "initial"
                      type        = string
                    }
                writeConnectionSecretToRef:
                  name: terraform-workspace-create-pipelinerun-id
            patches:
              - type: CombineFromComposite
                combine:
                  strategy: string
                  string:
                    fmt: 'create-piplinerunid-%s'
                  variables:
                    - fromFieldPath: metadata.name
                toFieldPath: metadata.name
              - type: CombineFromComposite
                combine:
                  strategy: string
                  string:
                    fmt: 'piplinerunid-%s'
                  variables:
                    - fromFieldPath: metadata.name
                toFieldPath: spec.writeConnectionSecretToRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: status.share.ips
                toFieldPath: spec.forProvider.vars[0].value
                policy:
                  fromFieldPath: Required
              - type: FromCompositeFieldPath
                fromFieldPath: spec.ansible.provisioningName
                toFieldPath: spec.forProvider.vars[1].value
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerRef.name
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerRef.kind
                toFieldPath: spec.providerConfigRef.kind
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.outputs.generated_id
                toFieldPath: status.share.pid
                policy:
                  fromFieldPath: Required
    - step: tekton-ansible-run
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: ansible-run
            base:
              apiVersion: resources.stuttgart-things.com/v1alpha1
              kind: AnsibleRun
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.namespace
                toFieldPath: metadata.namespace
              # TODO: Add to AnsibleRun definition - spec.inventory
              # - type: FromCompositeFieldPath
              #   fromFieldPath: status.share.ip
              #   toFieldPath: spec.inventory[0]
              #   policy:
              #     fromFieldPath: Required
              - type: CombineFromComposite
                combine:
                  strategy: string
                  string:
                    fmt: '%s-%s'
                  variables:
                    - fromFieldPath: metadata.name
                    - fromFieldPath: status.share.pid
                toFieldPath: spec.pipelineRunName
              # TODO: Field mismatch - definition uses spec.namespace
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.ansible.pipelineNamespace
              #   toFieldPath: spec.pipelineNamespace
              # TODO: Field mismatch - definition uses spec.ansibleWorkingImage
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.ansible.workingImage
              #   toFieldPath: spec.workingImage
              # TODO: Add to AnsibleRun definition - spec.vaultSecretName
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.ansible.vaultSecretName
              #   toFieldPath: spec.vaultSecretName
              - type: FromCompositeFieldPath
                fromFieldPath: spec.ansible.gitRepoUrl
                toFieldPath: spec.gitRepoUrl
              - type: FromCompositeFieldPath
                fromFieldPath: spec.ansible.gitRevision
                toFieldPath: spec.gitRevision
              - type: FromCompositeFieldPath
                fromFieldPath: spec.ansible.ansibleVarsFile
                toFieldPath: spec.ansibleVarsFile
              # TODO: Field mismatch - definition uses spec.ansibleExtraRoles
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.ansible.roles
              #   toFieldPath: spec.roles
              # TODO: Field mismatch - definition uses spec.ansibleExtraCollections
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.ansible.collections
              #   toFieldPath: spec.collections
              # TODO: Field mismatch - definition uses spec.ansiblePlaybooks
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.ansible.playbooks
              #   toFieldPath: spec.playbooks
              # TODO: Add to AnsibleRun definition - spec.providerRef
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.ansible.providerRef.name
              #   toFieldPath: spec.providerRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.ansible.createInventory
                toFieldPath: spec.createInventory
              # TODO: Add to AnsibleRun definition - spec.inventoryFile
              # - type: FromCompositeFieldPath
              #   fromFieldPath: status.share.ansible_inventory
              #   toFieldPath: spec.inventoryFile
              #   policy:
              #     fromFieldPath: Required
