---
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: pipelineintegrations.resources.stuttgart-things.com
spec:
  group: resources.stuttgart-things.com
  defaultCompositeDeletePolicy: Foreground
  scope: Namespaced
  names:
    kind: PipelineIntegration
    plural: pipelineintegrations
    singular: pipelineintegration
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: Platform-level pipeline offering with pluggable pipeline engines
          properties:
            spec:
              type: object
              required:
                - engine
              properties:
                engine:
                  type: object
                  required:
                    - type
                  properties:
                    type:
                      type: string
                      enum:
                        - tekton
                        - argo-workflows
                        - jenkins
                      description: Selected pipeline engine
                targetCluster:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                      description: Name of the ProviderConfig / ClusterProviderConfig
                    scope:
                      type: string
                      enum:
                        - Namespaced
                        - Cluster
                      default: Namespaced
                      description: |
                        Whether to use ProviderConfig (Namespaced)
                        or ClusterProviderConfig (Cluster)
                # --------------------
                # Tekton configuration
                # --------------------
                tekton:
                  type: object
                  properties:
                    namespace:
                      type: string
                      default: tekton-operator
                      description: Namespace for Tekton operator

                    pipelineNamespace:
                      type: string
                      default: tekton-pipelines
                      description: Default namespace for Tekton pipelines

                    version:
                      type: string
                      default: "0.77.5"
                      description: Tekton chart version

                    autoInstallComponents:
                      type: boolean
                      default: false
                      description: Automatically install Tekton components

                    imagePullPolicy:
                      type: string
                      enum: [Always, IfNotPresent, Never]
                      default: Always
                      description: Image pull policy for Tekton components

                    disableInlineSpec:
                      type: string
                      default: ""
                      description: Disable inline spec in Tekton

                    enableTektonPipeline:
                      type: boolean
                      default: true
                      description: Enable Tekton Pipeline component

                    enableTektonTriggers:
                      type: boolean
                      default: false
                      description: Enable Tekton Triggers component

                    enableTektonDashboard:
                      type: boolean
                      default: false
                      description: Enable Tekton Dashboard component

                    enableTektonPruner:
                      type: boolean
                      default: false
                      description: Enable automatic pruning of old pipeline runs

                    chartRepository:
                      type: string
                      default: "oci://ghcr.io/stuttgart-things/tekton"
                      description: OCI Helm chart repository

                # --------------------
                # Argo Workflows configuration
                # --------------------
                # argo:
                #   type: object
                #   properties:
                #     namespace:
                #       type: string
                #       default: argo-workflows
                #       description: Namespace for Argo Workflows

                #     version:
                #       type: string
                #       default: "0.44.0"
                #       description: Argo Workflows chart version

                #     server:
                #       type: object
                #       properties:
                #         enabled:
                #           type: boolean
                #           default: true
                #           description: Enable Argo Workflows server

                #         serviceType:
                #           type: string
                #           enum: [ClusterIP, NodePort, LoadBalancer]
                #           default: ClusterIP

                #     controller:
                #       type: object
                #       properties:
                #         workflowNamespaces:
                #           type: array
                #           items:
                #             type: string
                #           description: Namespaces where workflows can run

                #         persistence:
                #           type: object
                #           properties:
                #             archive:
                #               type: boolean
                #               default: false
                #               description: Enable workflow archiving

                #     artifactRepository:
                #       type: object
                #       properties:
                #         enabled:
                #           type: boolean
                #           default: false
                #           description: Enable artifact repository

                #         type:
                #           type: string
                #           enum: [s3, gcs, minio]
                #           default: s3

            status:
              type: object
              properties:
                installed:
                  type: boolean
                observedVersion:
                  type: string
                endpoint:
                  type: string

          # --------------------
          # CEL VALIDATIONS
          # --------------------
          x-kubernetes-validations:
            # targetCluster.scope must be valid
            - rule: |
                !has(self.spec.targetCluster.scope)
                || self.spec.targetCluster.scope in ['Namespaced', 'Cluster']
              message: "targetCluster.scope must be one of: Namespaced, Cluster"

            # name is always required
            - rule: |
                has(self.spec.targetCluster.name) && self.spec.targetCluster.name != ''
              message: "spec.targetCluster.name must be set"

            # ------------------------------------------------------------------
            # Engine-specific configuration requirements
            # ------------------------------------------------------------------

            # Tekton requires spec.tekton to be defined
            - rule: "self.spec.engine.type != 'tekton' || has(self.spec.tekton)"
              message: "spec.tekton must be defined when engine.type is 'tekton'"

            # (Future-proof) Argo requires spec.argo when enabled
            # - rule: "self.spec.engine.type != 'argo-workflows' || has(self.spec.argo)"
            #   message: "spec.argo must be defined when engine.type is 'argo-workflows'"

            # ------------------------------------------------------------------
            # Target cluster validation
            # ------------------------------------------------------------------

            # Target cluster reference must exist
            - rule: "has(self.spec.targetCluster)"
              message: "spec.targetCluster must be defined"

            # Target cluster name must be set
            - rule: "has(self.spec.targetCluster.name) && self.spec.targetCluster.name != ''"
              message: "spec.targetCluster.name must be set and non-empty"

            # ------------------------------------------------------------------
            # Tekton Pipeline component rules
            # ------------------------------------------------------------------

            # Tekton Pipelines enabled → pipelineNamespace must be set
            - rule: |
                self.spec.engine.type != 'tekton'
                || !self.spec.tekton.enableTektonPipeline
                || has(self.spec.tekton.pipelineNamespace)
              message: "tekton.pipelineNamespace must be set when Tekton Pipeline is enabled"

            # ------------------------------------------------------------------
            # Tekton Triggers rules
            # ------------------------------------------------------------------

            # Triggers require Tekton Pipelines
            - rule: |
                self.spec.engine.type != 'tekton'
                || !self.spec.tekton.enableTektonTriggers
                || self.spec.tekton.enableTektonPipeline
              message: "Tekton Triggers require enableTektonPipeline=true"

            # ------------------------------------------------------------------
            # Tekton Dashboard rules
            # ------------------------------------------------------------------

            # Dashboard requires Tekton Pipelines
            - rule: |
                self.spec.engine.type != 'tekton'
                || !self.spec.tekton.enableTektonDashboard
                || self.spec.tekton.enableTektonPipeline
              message: "Tekton Dashboard requires enableTektonPipeline=true"

            # ------------------------------------------------------------------
            # Tekton Pruner rules
            # ------------------------------------------------------------------

            # Pruner requires Tekton Pipelines
            - rule: |
                self.spec.engine.type != 'tekton'
                || !self.spec.tekton.enableTektonPruner
                || self.spec.tekton.enableTektonPipeline
              message: "Tekton Pruner requires enableTektonPipeline=true"

            # ------------------------------------------------------------------
            # Tekton version validation
            # ------------------------------------------------------------------

            # Version must be non-empty when Tekton is used
            - rule: |
                self.spec.engine.type != 'tekton'
                || (has(self.spec.tekton.version) && self.spec.tekton.version != '')
              message: "tekton.version must be set when engine.type is 'tekton'"

            # ------------------------------------------------------------------
            # Image pull policy validation (defensive, even with enum)
            # ------------------------------------------------------------------

            - rule: |
                self.spec.engine.type != 'tekton'
                || !has(self.spec.tekton.imagePullPolicy)
                || self.spec.tekton.imagePullPolicy in ['Always', 'IfNotPresent', 'Never']
              message: "tekton.imagePullPolicy must be one of: Always, IfNotPresent, Never"
