---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: VsphereVM
metadata:
  name: xplane-kind
  namespace: crossplane-system
spec:
  providerRef:
    name: vsphere-vm
  vm:
    count: "1"
    name: xplane-kind
    cpu: "8"
    ram: "4096"
    disk: "64"
    firmware: bios
    folderPath: stuttgart-things/testing
    datacenter: /LabUL
    datastore: /LabUL/datastore/UL-ESX-SAS-01
    resourcePool: /LabUL/host/Cluster-V6.5/Resources
    network: /LabUL/network/LAB-10.31.103
    template: sthings-u24
    bootstrap: '["echo STUTTGART-THINGS"]'
    annotation: VSPHERE-VM BUILD w/ CROSSPLANE FOR STUTTGART-THINGS
    unverifiedSsl: "true"
  tfvars:
    secretName: vsphere-tfvars # pragma: allowlist secret
    secretNamespace: crossplane-system # pragma: allowlist secret
    secretKey: terraform.tfvars # pragma: allowlist secret
  connectionSecret:
    name: xplane-kind
    namespace: crossplane-system
  compositionRef:
    name: vsphere-vm
