---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: AnsibleRun
  annotations:
    meta.crossplane.io/maintainer: patrick.hermann@sva.de
    meta.crossplane.io/source: https://github.com/stuttgart-things/crossplane
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      deploys AnsibleRun w/ crossplane
    meta.crossplane.io/readme: |
      deploys AnsibleRun w/ crossplane
spec:
  crossplane:
    version: ">=v2.1.3"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v1.2.0"
    # Required for Pipeline compositions
    - function: xpkg.upbound.io/crossplane-contrib/function-kcl
      version: ">=v0.12.0"
    - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
      version: ">=v0.6.0"
