---
apiVersion: vaultk8sauths.config.stuttgart-things.com/v1alpha1
kind: VaultK8sAuthClaim
metadata:
  name: vault-auth-custom-secret
  namespace: vault-system
spec:
  cluster_name: "production-cluster"
  vault_addr: "https://vault.production.com"
  providerConfigRef: "production-terraform-config"
  
  # Custom secret reference for different namespace/name
  secretRef:
    namespace: "vault-secrets"
    name: "production-vault-credentials"
    key: "terraform.tfvars.json"
  
  skip_tls_verify: false
  
  k8s_auths:
    - name: "workload-identity"
      namespace: "production"
      token_policies: ["production-policy", "workload-policy"]
      token_ttl: 7200
    
    - name: "admin-access"
      namespace: "admin-tools"
      token_policies: ["admin-policy"]
      token_ttl: 3600