---
apiVersion: config.stuttgart-things.com/v1alpha1
kind: VaultK8sAuth
metadata:
  name: vault-auth-claim
spec:
  compositionRef:
    name: vault-auth-composition
  cluster_name: "vcluster-tink2"
  vault_addr: "https://vault.demo-infra.sthings-vsphere.labul.sva.de"
  # providerConfigRef: "custom-terraform-config"  # Optional: use custom ProviderConfig
  
  # Optional: Custom secret reference (defaults to vault-credentials in current namespace)
  # secretRef:
  #   namespace: "vault-secrets"
  #   name: "custom-vault-credentials"
  #   key: "terraform.tfvars.json"
  
  k8s_auths:
    - name: dev
      namespace: default
      token_policies: ["read-all-s3-kvv2", "read-write-all-s3-kvv2"]
      token_ttl: 3600
    - name: cicd
      namespace: tektoncd
      token_policies: ["read-all-tektoncd-kvv2"]
      token_ttl: 3600
