---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: AnsibleRun
metadata:
  name: ansible-pipeline-test-6
  namespace: default
spec:
  pipelineRunName: run-ansible-test-6
  namespace: tekton-ci

  # Storage Configuration
  storageSize: "20Mi"
  storageAccessModes: ReadWriteOnce

  # Ansible Configuration
  ansibleWorkingImage: ghcr.io/stuttgart-things/sthings-ansible:11.11.0
  createInventory: "true"
  ansibleTargetHost: all
  ansibleVerbosity: "2"
  validateInventory: "true"

  # Git Configuration
  gitRepoUrl: https://github.com/stuttgart-things/stage-time.git
  gitRevision: main
  gitPath: pipelines/execute-ansible-playbooks.yaml
  gitWorkspaceSubdirectory: /ansible/workdir/

  # Credentials
  ansibleCredentialsSecretName: ansible-credentials
  ansibleCredentialsUserKey: ANSIBLE_USER
  ansibleCredentialsPasswordKey: ANSIBLE_PASSWORD

  # Ansible Roles and Collections
  installExtraRoles: "true"
  ansibleExtraRoles:
    - "https://github.com/stuttgart-things/install-requirements.git,2024.05.11"

  installExtraCollections: "true"
  ansibleExtraCollections:
    - "community.general:10.1.0"
    - "https://github.com/stuttgart-things/ansible/releases/download/sthings-baseos-25.4.118.tar.gz/sthings-baseos-25.4.118.tar.gz"

  # Playbooks and Variables
  ansiblePlaybooks:
    - "sthings.baseos.setup"

  ansibleVarsFile:
    - "manage_filesystem+-true"
    - "update_packages+-true"
    - "ansible_become+-true"
    - "ansible_become_method+-sudo"

  ansibleVarsInventory:
    - "all+[\"10.31.102.107\"]"

  # Crossplane Configuration
  wrapInCrossplane: true
  crossplaneObjectName: ansible-pipeline-test-6
  crossplaneNamespace: default
  crossplaneProviderConfig: kubernetes-provider
  crossplaneTimeout: "60"