---
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: clusterresourcepvcs.resources.stuttgart-things.com
spec:
  group: resources.stuttgart-things.com
  names:
    kind: ClusterResourcePVC
    plural: clusterresourcepvcs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfigRef:
                  type: string
                  description: "Name of the Kubernetes provider config"
                name:
                  type: string
                  description: "Name of the PVC"
                namespace:
                  type: string
                  description: "Namespace for the PVC"
                  default: "default"
                imageId:
                  type: string
                  description: "Harvester image ID for the annotation (e.g., default/image-t9w92)"
                storage:
                  type: string
                  description: "Storage size (e.g., 10Gi)"
                  default: "10Gi"
                storageClassName:
                  type: string
                  description: "Storage class name"
                accessModes:
                  type: array
                  description: "Access modes for the PVC"
                  items:
                    type: string
                  default:
                    - ReadWriteMany
                volumeMode:
                  type: string
                  description: "Volume mode (Block or Filesystem)"
                  default: "Block"
                annotations:
                  type: object
                  description: "Annotations to add to the PVC"
                  additionalProperties:
                    type: string
                additionalAnnotations:
                  type: object
                  description: "Additional annotations to add to the PVC"
                  additionalProperties:
                    type: string
                additionalLabels:
                  type: object
                  description: "Additional labels to add to the PVC"
                  additionalProperties:
                    type: string
              required:
                - providerConfigRef
                - name
                - storageClassName
            status:
              type: object
              properties:
                pvcName:
                  type: string
                  description: "Name of the created PVC"
                namespace:
                  type: string
                  description: "Namespace of the created PVC"
