---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: xgithubrunners.resources.stuttgart-things.com
  name: github-runner
spec:
  compositeTypeRef:
    apiVersion: resources.stuttgart-things.com/v1alpha1
    kind: XGithubRunner
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - base:
          apiVersion: helm.crossplane.io/v1beta1
          kind: Release
          metadata:
            annotations:
              crossplane.io/external-name: github-runner
            name: ghr
          spec:
            forProvider:
              chart:
                name: gha-runner-scale-set
                pullSecretRef:
                  name: ghcr
                  namespace: crossplane-system
                repository: oci://ghcr.io/actions/actions-runner-controller-charts
                version: 0.12.0
              insecureSkipTLSVerify: false
              namespace: arc-systems
              set:
              - name: githubConfigSecret.github_token
                valueFrom:
                  secretKeyRef:
                    key: GITHUB_TOKEN
                    name: github-flux-secrets
                    namespace: flux-system
              skipCRDs: true
              skipCreateNamespace: false
              values:
                containerMode:
                  kubernetesModeWorkVolumeClaim:
                    accessModes:
                    - ReadWriteOnce
                    resources:
                      requests:
                        storage: 50Mi
                    storageClassName: openebs-hostpath
                  type: kubernetes
                template:
                  spec:
                    containers:
                    - command:
                      - /home/runner/run.sh
                      env:
                      - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                        value: "false"
                      - name: ACTIONS_RUNNER_POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      image: ghcr.io/actions/actions-runner:2.323.0
                      name: runner
                    initContainers:
                    - args:
                      - |
                        whoami
                      command:
                      - /bin/sh
                      - -c
                      image: ghcr.io/actions/actions-runner:2.323.0
                      name: kube-init
                      volumeMounts:
                      - mountPath: /home/runner/_work
                        name: work
              wait: true
            providerConfigRef:
              name: in-cluster
        name: resource-0
        patches:
        - combine:
            strategy: string
            string:
              fmt: ghr-%s-%s
            variables:
            - fromFieldPath: spec.repository
            - fromFieldPath: spec.clusterConfig
          toFieldPath: metadata.name
          type: CombineFromComposite
        - combine:
            strategy: string
            string:
              fmt: ghr-%s-%s
            variables:
            - fromFieldPath: spec.repository
            - fromFieldPath: spec.clusterConfig
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          type: CombineFromComposite
        - combine:
            strategy: string
            string:
              fmt: https://github.com/%s/%s
            variables:
            - fromFieldPath: spec.group
            - fromFieldPath: spec.repository
          toFieldPath: spec.forProvider.values.githubConfigUrl
          type: CombineFromComposite
        - fromFieldPath: spec.clusterConfig
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.deploymentNamespace
          toFieldPath: spec.forProvider.namespace
          type: FromCompositeFieldPath
        - fromFieldPath: spec.version
          toFieldPath: spec.forProvider.chart.version
          type: FromCompositeFieldPath
        - fromFieldPath: spec.githubTokenSecret.name
          toFieldPath: spec.forProvider.set[0].valueFrom.secretKeyRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.githubTokenSecret.namespace
          toFieldPath: spec.forProvider.set[0].valueFrom.secretKeyRef.namespace
          type: FromCompositeFieldPath
        - fromFieldPath: spec.githubTokenSecret.key
          toFieldPath: spec.forProvider.set[0].valueFrom.secretKeyRef.key
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            strategy: string
            string:
              fmt: "%s:%s"
            variables:
            - fromFieldPath: spec.runnerImageRepo
            - fromFieldPath: spec.runnerImageTag
          toFieldPath: spec.forProvider.values.template.spec.containers[0].image
        - type: CombineFromComposite
          combine:
            strategy: string
            string:
              fmt: "%s:%s"
            variables:
            - fromFieldPath: spec.runnerImageRepo
            - fromFieldPath: spec.runnerImageTag
          toFieldPath: spec.forProvider.values.template.spec.initContainers[0].image
    step: patch-and-transform
  writeConnectionSecretsToNamespace: crossplane-system # pragma: allowlist secret
