---
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xgithubrunners.resources.stuttgart-things.com
spec:
  group: resources.stuttgart-things.com
  defaultCompositeDeletePolicy: Foreground
  scope: Namespaced
  names:
    kind: XGithubRunner
    plural: xgithubrunners
    singular: xgithubrunner
  claimNames:
    kind: GithubRunner
    plural: githubrunners
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: A GithubRunner is a composite resource that represents a helm release for a github runner deployment
          properties:
            spec:
              type: object
              properties:
                targetCluster:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                      default: in-cluster
                      description: Name of the ProviderConfig / ClusterProviderConfig
                    scope:
                      type: string
                      enum:
                        - Namespaced
                        - Cluster
                      default: Namespaced
                      description: |
                        Whether to use ProviderConfig (Namespaced)
                        or ClusterProviderConfig (Cluster)
                githubTokenSecret:
                  type: object
                  properties:
                    name:
                      type: string
                      default: github
                    namespace:
                      type: string
                      default: crossplane-system
                    key:
                      type: string
                      default: GITHUB_TOKEN
                  required: [name, namespace, key]
                deploymentNamespace:
                  type: string
                  default: arc-systems
                  description: namespace of runner (release)
                repository:
                  type: string
                  description: github repository name
                runnerImageRepo:
                  type: string
                  default: ghcr.io/actions/actions-runner
                runnerImageTag:
                  type: string
                  default: "2.331.0"
                group:
                  type: string
                  default: stuttgart-things
                  description: github group name
                version:
                  type: string
                  default: "0.13.1"
                  description: helm chart version for github-runner
              required:
                - repository
                - githubTokenSecret
            status:
              type: object
              properties:
                installed:
                  type: boolean
                  description: Whether the github-runner is installed
