---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgithubrunners.resources.stuttgart-things.com
spec:
  connectionSecretKeys:
    - kubeconfig
  group: resources.stuttgart-things.com
  names:
    kind: XGithubRunner
    plural: xgithubrunners
  claimNames:
    kind: GithubRunner
    plural: githubrunners
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A GithubRunner is a composite resource that represents a helm release for a github runner deployment
          type: object
          properties:
            spec:
              type: object
              properties:
                githubTokenSecret:
                  type: object
                  properties:
                    name:
                      type: string
                      default: github
                    namespace:
                      type: string
                      default: crossplane-system
                    key:
                      type: string
                      default: GITHUB_TOKEN
                  required: [name, namespace, key]
                deploymentNamespace:
                  type: string
                  default: arc-systems
                  description: namespace of runner (release)
                repository:
                  type: string
                  description: github repository name
                runnerImageRepo:
                  type: string
                  default: ghcr.io/actions/actions-runner
                runnerImageTag:
                  type: string
                  default: 2.323.0
                group:
                  type: string
                  default: stuttgart-things
                  description: github group name
                version:
                  type: string
                  default: 0.11.0
                  description: helm chart version for github-runner
                clusterConfig:
                  type: string
                  default: in-cluster
                  description: cluster name/helm provider name
              required:
                - repository
                - githubTokenSecret
