---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: XGithubRunner
metadata:
  name: ansible-in-cluster
spec:
  targetCluster:
    name: in-cluster
    scope: Namespaced
  group: stuttgart-things
  repository: ansible
  version: "0.13.1"
  runnerImageTag: "2.331.0"
  githubTokenSecret:
    name: github
    namespace: crossplane-system
    key: GITHUB_TOKEN
