---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: proxmox-vm
  annotations:
    meta.crossplane.io/maintainer: patrick.hermann@sva.de
    meta.crossplane.io/source: github.com/stuttgart-things/crossplane
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      creates proxmox-vm with crossplane based on opentofu (provider)
    meta.crossplane.io/readme: |
      creates proxmox-vm with crossplane based on opentofu (provider)
spec:
  crossplane:
    version: ">=2.13.0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-opentofu
      version: ">=v0.3.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.9.3"
