---
# BASE-OS
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: AnsibleRun
metadata:
  name: install-golang
  namespace: crossplane-system
spec:
  pipelineRunName: install-golang-6
  createInventory: "false"
  varsFile: bmFtZToga29sbGUK # pragma: allowlist secret
  inventoryFile: MTAuMzEuMTAxLjE1OAo= # pragma: allowlist secret
  playbooks:
    - "sthings.baseos.prepare_env"
    - "sthings.baseos.golang"
  ansibleVarsFile:
    - golang_version+-1.24.0
    - manage_filesystem+-true
    - update_packages+-true
    - install_requirements+-true
    - install_motd+-true
    - username+-sthings
    - lvm_home_sizing+-'15%'
    - lvm_root_sizing+-'35%'
    - lvm_var_sizing+-'50%'
    - send_to_msteams+-true
    - reboot_all+-false
  gitRepoUrl: https://github.com/stuttgart-things/ansible.git
  gitRevision: main
  providerRef:
    name: kubernetes-incluster
  vaultSecretName: vault # pragma: allowlist secret
  pipelineNamespace: tekton-pipelines
  workingImage: ghcr.io/stuttgart-things/sthings-ansible:11.3.0-3
  collections:
    - community.crypto:2.22.3
    - community.hashi_vault:6.2.0
    - ansible.netcommon:7.1.0
    - https://github.com/stuttgart-things/ansible/releases/download/sthings-baseos-25.3.1202.tar.gz/sthings-baseos-25.3.1202.tar.gz
    - https://github.com/stuttgart-things/ansible/releases/download/sthings-container-25.6.1311.tar.gz/sthings-container-25.6.1311.tar.gz
    # - https://artifacts.homerun-dev.sthings-vsphere.labul.sva.de/ansible-collections/sthings-deploy_rke-24.2843.39.tar.gz
    # - https://github.com/stuttgart-things/stuttgart-things/releases/download/0.0.86/sthings-awx-0.0.86.tar.gz
    # - https://artifacts.homerun-dev.sthings-vsphere.labul.sva.de/ansible-collections/sthings-base_os-24.21.29.tar.gz
