# BASE-OS
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: AnsibleRun
metadata:
  name: dev-vm-bins
  namespace: crossplane-system
spec:
  pipelineRunName: dev-vm-bins2
  inventory:
    - "all+[\"10.31.102.188\"]"
  createInventory: "true"
  playbooks:
    - plays/prepare-env.yaml
    - sthings.baseos.binaries
  ansibleVarsFile:
    - manage_filesystem+-true
    - update_packages+-true
    - install_requirements+-true
    - install_motd+-true
    - username+-sthings
    - lvm_home_sizing+-'15%'
    - lvm_root_sizing+-'35%'
    - lvm_var_sizing+-'50%'
    - send_to_msteams+-true
    - reboot_all+-false
  gitRepoUrl: https://github.com/stuttgart-things/ansible.git
  gitRevision: main
  providerRef:
    name: in-cluster
  vaultSecretName: vault # pragma: allowlist secret
  pipelineNamespace: tekton-pipelines
  workingImage: ghcr.io/stuttgart-things/sthings-ansible:11.3.0-3
  roles:
    - "https://github.com/stuttgart-things/install-requirements.git,2024.05.11"
  collections:
    - community.crypto:2.22.3
    - community.general:10.1.0
    - ansible.posix:2.0.0
    - kubernetes.core:5.0.0
    - community.docker:4.1.0
    - community.vmware:5.2.0
    - awx.awx:24.6.1
    - community.hashi_vault:6.2.0
    - ansible.netcommon:7.1.0
    - https://github.com/stuttgart-things/ansible/releases/download/sthings-baseos-25.3.496.tar.gz/sthings-baseos-25.3.496.tar.gz
    - https://github.com/stuttgart-things/ansible/releases/download/sthings-container-25.3.497.tar.gz/sthings-container-25.3.497.tar.gz
