---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: PipelineIntegration
  annotations:
    meta.crossplane.io/maintainer: patrick.hermann@sva.de
    meta.crossplane.io/source: https://github.com/stuttgart-things/crossplane
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      manages lifecycle of PipelineIntegration w/ crossplane
    meta.crossplane.io/readme: |
      manages lifecycle of PipelineIntegration w/ crossplane
spec:
  crossplane:
    version: ">=v2.1.3"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v1.0.6"
